import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const repositoryRoot = resolve(import.meta.dir, "..");
const sourcePath = resolve(repositoryRoot, "packages/contracts/src/analytics-registry.v1.json");
const destinationPath = resolve(repositoryRoot, "frontend/src/lib/analyticsRegistry.generated.ts");

const source = JSON.parse(await readFile(sourcePath, "utf8"));
const output = `// Generated by scripts/generate-frontend-analytics-registry.ts.
// Source of truth: packages/contracts/src/analytics-registry.v1.json.
// Do not edit this file directly.

export const analyticsRegistry = ${JSON.stringify(source, null, 2)} as const;
`;

await writeFile(destinationPath, output, "utf8");
