import type { ApplicationDraft, ApplicationSubmissionPlan, ApplicationSubmissionReceipt, AtsAdapterCapabilities, CandidateEvidenceItem, CandidateEvidenceSnapshot, JobSnapshot } from '@hirly/application-agent-contracts';
import type { ApplicationModelGateway, AtsAdapter, AtsCapabilityRegistry, CandidateEvidenceStore, ClaimSupportVerifier, JobSourceReader, JobSnapshotStore, ApplicationDraftStore, SubmissionPlanStore, SubmissionReceiptStore, ApprovalReviewStore, ApprovalReviewRecord, AuditOutboxPublisher } from './ports';
import { sha256 } from './core';

export const memoryStore = <T extends { id: string }>(values: T[] = []) => { const valuesById = new Map(values.map((v) => [v.id, v])); return { async get(id: string) { return valuesById.get(id); }, async put(value: T) { valuesById.set(value.id, value); }, values: valuesById }; };
export const memoryEvidenceStore = (snapshot: CandidateEvidenceSnapshot, items: CandidateEvidenceItem[]): CandidateEvidenceStore => ({ async getSnapshot(id) { return id === snapshot.id ? snapshot : undefined; }, async getItems(ids) { return items.filter((item) => ids.includes(item.id)); } });
export const memoryReceiptStore = () => { const values = new Map<string, ApplicationSubmissionReceipt>(); return { async get(planId: string) { return values.get(planId); }, async put(value: ApplicationSubmissionReceipt) { values.set(value.planId, value); }, values }; };
export const fixtureJobReader = (job: JobSnapshot): JobSourceReader => ({ async read(input) { if (input.fixtureId === 'fixture_job-a') return job; throw new Error('INVALID_JOB_URL'); } });
export const fixtureModel: ApplicationModelGateway = { async createDraft({ snapshot, job, evidence }) { const supported = evidence[0]; return { id: 'draft_fixture-a', version: 1, candidateSnapshotFingerprint: snapshot.snapshotFingerprint, jobSnapshotFingerprint: job.sourceFingerprint, secureContentRef: 'vault:draft-fixture-a', claims: supported ? [{ id: 'claim_typescript', evidenceId: supported.id, supportStatus: 'supported', verifierReasonCodes: [], confidence: supported.confidence }] : [], unresolvedCandidateQuestionIds: job.questions.filter((question) => question.candidateOnly && question.mandatory).map((question) => question.id), status: job.questions.some((question) => question.candidateOnly && question.mandatory) ? 'candidate_input_required' : 'ready', createdAt: '2026-01-01T00:00:00.000Z' }; } };
export const fixtureVerifier: ClaimSupportVerifier = { async verify(draft, evidence) { const supports = draft.claims.map((claim) => ({ claimId: claim.id, evidenceIds: [claim.evidenceId], status: evidence.some((item) => item.id === claim.evidenceId) ? 'supported' as const : 'unsupported' as const, verifierIdentity: 'fixture-verifier', verifierVersion: '1', safeEvidenceRefs: ['evidence:fixture-typescript'] })); const blockedReasonCodes = [ ...(!supports.every((s) => s.status === 'supported') ? ['UNSUPPORTED_APPLICATION_CLAIM'] : []), ...(draft.unresolvedCandidateQuestionIds.length ? ['MISSING_CANDIDATE_INPUT'] : []) ]; return { supports, blockedReasonCodes }; } };
export const fixtureCapabilities: AtsAdapterCapabilities = { readJob: true, extractRequirements: true, fillTextFields: true, uploadCv: true, answerCustomQuestions: true, submit: true, captchaSupport: false, submissionApprovalRequired: true };
export const controlledAtsSimulator = (): AtsAdapter & { mutations: number } => { let mutations = 0; let confirmed = new Set<string>(); return { key: 'fixture-ats', version: '1.0.0', capabilities: fixtureCapabilities, get mutations() { return mutations; }, async submit(plan) { mutations += 1; confirmed.add(plan.id); return { providerApplicationId: 'provider:fixture-application' }; }, async readBack(plan) { return confirmed.has(plan.id) ? { confirmed: true, evidenceRef: 'receipt:fixture-confirmation' } : { confirmed: false }; } }; };
export const fixtureAdapterRegistry = (adapter: AtsAdapter): AtsCapabilityRegistry => ({ get: (key, version) => adapter.key === key && adapter.version === version ? adapter : undefined });
export const memoryReviewStore = (records: ApprovalReviewRecord[]): ApprovalReviewStore => { const byRef = new Map(records.map((record) => [record.ref, record])); return { async get(ref) { return byRef.get(ref); } }; };
export const memoryOutbox = (): AuditOutboxPublisher & { events: Array<{ key: string; version: string; payload: unknown }> } => { const events: Array<{ key: string; version: string; payload: unknown }> = []; return { events, async publish(event) { events.push(event); } }; };
export type RuntimeMemoryStores = { jobs: ReturnType<typeof memoryStore<JobSnapshot>>; drafts: ReturnType<typeof memoryStore<ApplicationDraft>>; plans: ReturnType<typeof memoryStore<ApplicationSubmissionPlan>>; receipts: ReturnType<typeof memoryReceiptStore> };
