/** In-app UI copy for /app routes (English + French). */

import { readAiSettings } from "./aiSettings";

export const APP_UI = {
  en: {
    common: {
      back: "Back",
      cancel: "Cancel",
      save: "Save",
      add: "Add",
      clear: "Clear",
      refresh: "Refresh feed",
      loading: "Loading…",
      notSet: "Not set",
      yes: "Yes",
      no: "No",
      account: "Account",
      platform: "Platform",
      support: "Support",
      credits: "Credits",
      unlimited: "Unlimited",
      language: "Language",
      english: "English",
      french: "French",
    },
    accountMenu: {
      account: "Account",
      billing: "Billing",
      logOut: "Log out",
    },
    billingPage: {
      title: "Billing & Subscription",
      currentSubscription: "Current Subscription",
      currentSubscriptionDesc: "Subscribe to unlock premium features and unlimited applications.",
      noSubscription: "No Active Subscription",
      noSubscriptionDesc: "Subscribe to get access to premium features, AI-powered resumes, and unlimited applications.",
      viewPlans: "View Plans & Subscribe",
      manageSubscription: "Manage Subscription",
      premiumActive: "Premium Active",
      premiumActiveDesc: "Your subscription is active. Manage billing details in the customer portal.",
      mobileSubscriptionTitle: "Have a mobile subscription?",
      mobileSubscriptionDesc: "If you purchased a subscription through the mobile app, link your account to manage it here.",
      linkMobilePurchase: "Link Mobile Purchase",
      usageCredits: "Usage & Credits",
      usageCreditsDesc: "Track your credit usage and see how many credits you have remaining for this period.",
      currentCreditPeriod: "Current Credit Period",
      creditsUsed: "Credits Used",
      creditsOf: "{used} of {total} credits",
      usedThisPeriod: "used this period",
      usageProgress: "Usage Progress",
      remaining: "{n} remaining",
      getMoreCredits: "Get More Credits",
      getMoreCreditsDesc: "Subscribe to get more credits for your job search",
      subscribeNow: "Subscribe Now",
      dailyUsage: "Daily Usage Breakdown",
      daysShown: "{n} days shown",
      past7Days: "Past 7 days",
      past14Days: "Past 14 days",
      past30Days: "Past 30 days",
      applications: "Applications",
    },
    nav: {
      feed: "Feed",
      jobs: "Jobs",
      review: "Review",
      applications: "Applications",
      inbox: "Inbox",
      profile: "Profile",
      aiSettings: "AI Settings",
    },
    swipe: {
      pass: "Pass",
      apply: "Apply",
      passStamp: "PASS",
      skipStamp: "PASS",
      applyStamp: "APPLY",
      tapForDetails: "Tap for details",
      tapToFlipBack: "Tap to flip back",
      swipeHint: "Swipe or tap · Tap card for details",
      jobTitle: "Job title",
      location: "Location",
      postedToday: "Posted today",
      postedOneDay: "Posted 1 day ago",
      postedDays: "Posted {n} days ago",
      postedRecently: "Posted recently",
      locationNotSpecified: "Location not specified",
      aboutRole: "About This Role",
      whyFits: "Why this fits you",
      requiredQualifications: "Required Qualifications",
      techStack: "Tech stack",
      noJobs: "No jobs found",
      noJobsFilters: "No one-swipe jobs found with these filters.",
      couldNotLoad: "Could not load jobs.",
      setTargetRole: "Set target role",
      anywhere: "Anywhere",
      tapToEdit: "tap to edit",
      openFilters: "Open filters",
      undoSwipe: "Undo last swipe",
      history: "History",
      reportJob: "Report job",
      shareJob: "Share job",
      entryLevel: "Entry Level",
      midLevel: "Mid Level",
      senior: "Senior",
      lead: "Lead",
      principal: "Principal",
      fullTime: "Full Time",
      remote: "Remote",
      hybrid: "Hybrid",
      inPerson: "In Person",
      switchLight: "Switch to light mode",
      switchDark: "Switch to dark mode",
      notifications: "Notifications",
      feedTimeout: "Jobs feed is taking too long. Try refreshing or widening your filters.",
      providerRateLimited: "Job provider is temporarily rate-limited. Try again later or widen filters.",
      widenFiltersHint: "Try widening your distance, adding more locations, or choosing another role.",
      tryWidenSearch: "Try widening your search distance or changing your location.",
      editTarget: "Edit target role and location",
      swipeReadyReview: "Ready for your review",
      swipeAppPrepared: "Application prepared",
      swipeWaitingReview: "{company} is waiting in Review. Approve the documents to submit.",
      swipeReadyApps: "{company} is ready in Applications. Not submitted yet.",
      swipeActionRequiredDesc: "Open Tracker to answer the remaining application questions.",
      swipeHumanVerification: "Human verification needed",
      swipeHumanVerificationDesc: "Open Tracker to complete the manual verification step.",
      swipePackageGenerated: "Application package generated",
      swipePackageFailed: "Browser preparation failed. You can retry from Tracker.",
      swipeTextGenerated: "Application text generated",
      swipeTextGeneratedDesc: "CV and cover letter text are ready, but the file package needs review.",
      swipeMoreProfile: "More profile data needed",
      swipeMoreProfileDesc: "Complete your CV/profile to generate a stronger application.",
      swipeMoreJob: "More job data needed",
      swipeMoreJobDesc: "This job post does not include enough detail for a strong tailored package.",
      swipeAppSaved: "Application saved",
      swipeAppSavedDesc: "Generation failed. Open Tracker to review or retry later.",
      swipeQueued: "Application queued for {company}",
      swipeQueuedDesc: "We are generating the tailored CV and cover letter in the background.",
      swipePackageFor: "Application package generated for {company}",
      swipePackageReady: "CV and cover letter are ready. Not submitted yet.",
      demoApplied: "Applied (demo)",
      demoAppliedDesc: "Demo mode — your application was saved locally. Nothing was sent to the company.",
      generationTimeout: "Application generation is still taking longer than expected. Check Tracker in a moment.",
      noJobsFiltered: "No jobs found with these filters.",
      industryProductDesign: "Product Design",
      industryInfrastructure: "Infrastructure",
      industryAiMl: "AI / ML",
      industryMarketing: "Marketing",
      industryTechnology: "Technology",
      companySize11: "11-50 employees",
      companySize51: "51-500 employees",
      companySize501: "501-1000 employees",
      companySize1001: "1001-5000 employees",
    },
    filters: {
      title: "Filters",
      postedDate: "Posted Date",
      workLocation: "Work Location",
      experience: "Experience",
      jobType: "Job Type",
      salary: "Salary",
      company: "Company",
      industry: "Industry",
      includeUnknownLocation: "Include unknown work location",
      includeUnknownSalary: "Include unknown salary",
      minimum: "Minimum:",
      onlyCompanies: "Only show jobs from",
      hideCompanies: "Hide jobs from",
      onlyIndustries: "Only show jobs in",
      hideIndustries: "Hide jobs in",
      companyPlaceholder: "Company name",
      industryPlaceholder: "Industry name",
      removeValue: "Remove {value}",
      clear: "Clear filters",
      dateAny: "Any time",
      date1d: "Past 24 hours",
      date7d: "Past week",
      date30d: "Past month",
      workOnsite: "In Person",
      workHybrid: "Hybrid",
      workRemote: "Remote",
      jobFullTime: "Full Time (CDI)",
      jobPartTime: "Part Time",
      jobInternship: "Internship",
      jobFixedTerm: "Fixed-term (CDD)",
      jobApprenticeship: "Apprenticeship",
      jobSummer: "Summer job",
      jobSeasonal: "Seasonal",
      jobFreelance: "Freelance",
      expEntry: "Entry Level",
      expMid: "Mid Level",
      expSenior: "Senior Level",
      expExecutive: "Executive Level",
    },
    settings: {
      title: "Settings",
      lookAndFeel: "Look & feel",
      theme: "Theme",
      alerts: "Alerts",
      notificationPrefs: "Notification preferences",
      walkthrough: "Walkthrough",
      replayWalkthrough: "Replay walkthrough",
      privacyData: "Privacy & data",
      privacyPolicy: "Privacy policy",
      termsOfUse: "Terms of use",
      planHelp: "Plan & help",
      manageBilling: "Manage billing",
      upgradePlan: "Upgrade your plan",
      restorePurchase: "Restore purchase",
      talkToUs: "Talk to us",
      shareBrand: "Share {brand}",
      inviteFriend: "Invite a friend",
      onInstagram: "We're on Instagram",
      onTikTok: "We're on TikTok",
      yourAccount: "Your account",
      signOut: "Sign out",
      deleteAccount: "Delete account",
      userId: "User ID",
      comingSoon: "{feature} — coming soon",
      inviteCopied: "Invite link copied",
      billingPortalError: "Could not open billing portal",
      deleteConfirm: "Delete your Hirly account? This removes your profile, swipes, and applications. This cannot be undone.",
      accountDeleted: "Account deleted",
      deleteError: "Could not delete account",
      languageTitle: "App language",
      languageDesc: "Choose the language for menus, buttons, and job cards.",
      languageSetEn: "Language set to English",
      languageSetFr: "Language set to French",
    },
    aiSettings: {
      poweredBy: "Powered by {brand} AI",
      title: "AI Settings",
      subtitle: "AI Application Settings",
      description: "Choose how AI assists with your job applications — speed, quality, and control in one place.",
      featuresOn: "{n}/4 features on",
      swipeReady: "1-swipe apply ready",
      promoTitle: "Built for screen recordings",
      promoBody: "Clean layout · instant toggles · recruiter-grade output",
      automation: "Automation",
      coverLetter: "AI Cover Letter",
      coverLetterDesc: "Generate a tailored cover letter for each job application",
      coverLetterStat: "~90 sec saved",
      resume: "AI Resume",
      resumeDesc: "Generate a tailored resume for each job application",
      resumeStat: "ATS-optimized",
      reviewDocs: "Review Documents",
      reviewDocsDesc: "Review and approve AI-generated documents before they are used in applications",
      reviewDocsStat: "Full control",
      findGaps: "Find Gaps in Resume",
      findGapsDesc: "Answer questions addressing job requirements to improve AI resume and cover letter generation",
      findGapsStat: "Smarter matches",
      mobileIntro: "Choose how AI assists with your job applications.",
    },
    demoSettings: {
      sectionTitle: "Demo mode",
      sectionIntro: "Sample finance jobs in Paris for screen recordings and product demos.",
      financeJobFeed: "Finance jobs (Paris)",
      financeJobFeedDesc: "Replace the live feed with 30 realistic banking & markets roles (BNP, SocGen, Natixis, etc.). Applies stay local.",
      financeJobFeedOn: "Finance demo feed enabled",
      financeJobFeedOff: "Finance demo feed disabled",
    },
    demo: {
      badge: "Demo account",
      banner: "Applications stay local for screen recordings. Nothing is submitted to employers.",
    },
    credits: {
      viewPlans: "View plans",
      unlimitedAria: "Unlimited credits",
    },
    review: {
      title: "Review",
      subtitleOn: "Approve tailored documents before they are submitted.",
      subtitleOff: "Turn on Review Documents in AI Settings to queue applications here.",
      disabledTitle: "Document review is off",
      openAiSettings: "Open AI Settings",
      allCaughtUp: "All caught up",
      backToJobs: "Back to jobs",
      readyToReview: "Ready to review",
      generatedRecently: "Generated recently",
      generatedOn: "Generated {date}",
      dialogHint: "Review the generated CV and cover letter below. Approve to submit this application.",
      cv: "CV",
      coverLetter: "Cover letter",
      approveSubmit: "Approve & Submit",
      loadError: "Could not load applications",
      openError: "Could not open application",
      submitted: "Application submitted",
      actionRequired: "Action required",
      approved: "Application approved",
      submitError: "Could not submit application",
      disabledBody: "Applications are prepared automatically when you swipe right. Turn on Review Documents to approve each package before it is submitted.",
      emptyBody: "No applications are waiting for your review. Swipe right on jobs to generate new packages.",
      approvedDesc: "We are finalizing the submission.",
      actionRequiredDesc: "A few answers are needed before this can be completed.",
    },
    tracker: {
      title: "Applications",
      subtitle: "Track packages, submissions, and follow-ups in one place.",
      addResume: "Add Your Resume",
      addResumeBody: "Upload your main resume to activate job applications and track your progress.",
      uploadResume: "Upload Resume",
      yourApplications: "Your applications",
      summary: "Summary",
      nextAction: "Next action",
      generatedDocs: "Generated documents",
      timeline: "Timeline",
      whyFit: "Why you fit",
      searchPlaceholder: "Search company, job, or location",
      nothingYet: "Nothing here yet",
      noSearchMatch: "No applications match your search.",
      backToSwipe: "Back to swipe",
      totalApplications: "Total applications",
      successRate: "Success rate",
      pending: "Pending",
      actionRequired: "Action required",
      all: "All",
      prepared: "Prepared",
      ready: "Ready",
      submitted: "Submitted",
      applied: "Applied",
      failed: "Failed",
      expired: "Expired",
      untitledRole: "Untitled role",
      unknownCompany: "Unknown company",
      securityCheck: "Security check needed",
      needsAttention: "Needs attention",
      appPending: "Application pending",
      answerQuestions: "Answer questions",
      viewIssue: "View issue",
      finalizing: "Finalizing",
      generated: "Generated",
      today: "Today",
      yesterday: "Yesterday",
      daysAgo: "{n} days ago",
      oneWeekAgo: "1 wk ago",
      weeksAgo: "{n} wks ago",
      atsUnknown: "ATS unknown",
      emptyAll: "No applications yet. Swipe right on jobs to start tracking them here.",
      emptyActionRequired: "No applications need answers right now.",
      emptyPending: "No pending applications right now.",
      emptySubmitted: "No submitted applications yet.",
      emptyPrepared: "No prepared applications right now.",
      emptyFailed: "No failed applications right now.",
      emptyExpired: "No expired applications.",
      emptyDefault: "No applications found.",
      timelineCreated: "Application created",
      timelinePackage: "Tailored package generated",
      timelineSubmitted: "Application submitted",
      timelineAnswersNeeded: "Answers needed",
      timelinePending: "Application pending",
      timelinePrepared: "Application prepared",
      timelineSecurity: "Security check needed",
      timelineFailed: "Needs attention",
      timelineExpired: "Application expired",
      statusSubmitted: "Submitted",
      statusFinalizing: "We're finalizing your application.",
      statusPrepared: "Application prepared. Final submission is not enabled yet.",
      statusBlocked: "A few answers are needed before this application can be prepared.",
      statusCaptcha: "An additional security check is required before this application can be completed.",
      statusPrepareFailed: "Application package generated, but browser preparation failed.",
      statusFailed: "Submission failed.",
      statusUnknown: "Submission status is unknown. Review before continuing.",
      statusNotSubmitted: "Not submitted yet",
      cvDownloaded: "CV downloaded",
      coverDownloaded: "Cover letter downloaded",
      submittedCount: "{n} submitted",
      submittedOverTotal: "submitted / total",
      beingFinalized: "being finalized",
      needAttentionCount: "{n} need attention",
      locationNotListed: "Location not listed",
      recently: "recently",
      updated: "Updated {date}",
      applied: "Applied {date}",
      available: "Available",
      skippedJobs: "Skipped jobs",
      listApplying: "Applying…",
      listViewApplication: "View application",
      listViewPackage: "View package",
      listAnswerQuestions: "Answer questions",
      listSecurityCheck: "Security check",
      listViewDetails: "View details",
    },
    history: {
      generated: "Generated",
      passed: "Passed",
      passedTitle: "Jobs you passed",
      generatedTitle: "Generated packages",
      subtitle: "Review generated packages and jobs you passed.",
      generatePackage: "Generate Package",
      noPassed: "No passed jobs yet.",
      noGenerated: "No generated jobs yet.",
      loadError: "Failed to load history",
      packageGenerated: "Application package generated. Not submitted yet.",
      packageError: "Could not generate package. Try again.",
    },
    emails: {
      searchMail: "Search in mail",
      primary: "Primary",
      verification: "Verification",
      interview: "Interview",
      offer: "Offer",
      inboxTitle: "Inbox",
      inboxSubtitle: "Interview invites, offers, and application updates.",
      emptyFolder: "No messages in this folder.",
      newOutreach: "New outreach email",
      emailType: "Email type",
      application: "Application",
      preview: "Preview",
      generate: "Generate",
      copySaveDraft: "Copy & Save as Draft",
      saved: "Saved",
      noDrafts: "No drafts yet. Generate an outreach email to save a draft.",
      connectGmail: "Connect Gmail",
      syncInbox: "Sync your inbox to see replies here.",
      comingSoon: "Coming soon",
      reply: "Reply",
      archive: "Archive",
      markUnread: "Mark unread",
      more: "More",
      back: "Back",
      toMe: "to me",
      writeReply: "Write your reply…",
      send: "Send",
      copiedDraft: "Copied and saved as draft",
      writeReplyFirst: "Write a reply first",
      cantReply: "You can't reply to this message",
      markedUnread: "Marked as unread",
      archived: "Message archived",
      reportThanks: "Report submitted — thanks for letting us know",
      replySent: "Reply sent",
      copied: "Copied to clipboard",
      draftDeleted: "Draft deleted",
      sent: "Sent",
      replied: "Replied",
      composeEmail: "Compose email",
      system: "System",
      copy: "Copy",
      addedStarred: "Added to starred",
      removedStarred: "Removed from starred",
    },
    profile: {
      title: "Profile",
      subtitle: "Resume, personal info, and application defaults.",
      resume: "Resume",
      personal: "Personal Info",
      files: "Files",
      documentsTab: "Documents",
      yourCv: "Your CV",
      resumeUploaded: "Resume uploaded — tap to update",
      uploadResume: "Upload your resume",
      completeProfile: "Complete your profile",
      completeProfileBody: "Auto-fill more job application fields.",
      finishProfile: "Finish profile",
      upgradePlan: "Upgrade your plan",
      unlimitedSwipes: "Unlimited swipes",
      creditsRemaining: "Application credits remaining",
      jobPreferences: "Job Preferences",
      targetLocation: "Target location",
      remotePreference: "Remote preference",
      seniority: "Seniority",
      applicationDefaults: "Application defaults",
      personalDetails: "Personal details",
      addYourName: "Add your name",
      otherFiles: "Other files",
      otherFilesHint: "Transcripts, portfolios, certificates…",
      preferencesSaved: "Preferences saved",
      preferencesError: "Could not save preferences",
      defaultsSaved: "Application defaults saved",
      defaultsError: "Could not save application defaults",
      selectLocation: "Select a location from the suggestions",
      extractedData: "Extracted application data",
      extractedDataHint: "Reusable CV details used for job forms",
      applicationDefaultsHint: "Reusable answers for one-swipe applications",
      any: "Any",
      remoteOnly: "Remote only",
      onsite: "On-site",
      personalInfo: {
        contactTitle: "Contact Information",
        contactDesc: "Your basic contact details for professional communication and applications.",
        salaryTitle: "Salary Expectations",
        salaryDesc: "Set your salary expectations to help match you with appropriate job opportunities.",
        demographicsTitle: "Demographic Information",
        demographicsDesc: "Help us understand your background and preferences to provide a better experience.",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        phone: "Phone",
        address: "Address",
        minimum: "Minimum",
        maximum: "Maximum",
        salarySummary: "Looking for positions paying {min} - {max} annually",
        dateOfBirth: "Date of Birth",
        gender: "Gender",
        ethnicity: "Ethnicity",
        disabilityStatus: "Disability Status",
        sexualOrientation: "Sexual Orientation",
        veteranStatus: "Veteran Status",
        citizenshipStatus: "Citizenship Status",
        selectGender: "Select gender",
        selectStatus: "Select status",
        selectOrientation: "Select orientation",
        editAddress: "Edit address",
        clearAddress: "Clear address",
        addCitizenship: "Add citizenship status",
        citizenshipCountry: "Country or region",
        citizenshipType: "Status type",
        removeCitizenship: "Remove citizenship entry",
        noCitizenship: "No citizenship status",
        noCitizenshipDesc: "Add your citizenship or visa status to help employers understand your work authorization.",
        contactSaved: "Contact information saved",
        salarySaved: "Salary expectations saved",
        demographicsSaved: "Demographic information saved",
        saveError: "Could not save changes",
      },
      documents: {
        resumeTitle: "Resume",
        resumeSectionDesc: "Your primary resume used to build your profile and generate tailored applications.",
        noResume: "No resume uploaded yet",
        noResumeDesc: "Upload your resume to build your professional profile and generate tailored applications.",
        uploadResume: "Upload resume",
        resumeOnFile: "Current resume on file",
        replaceResume: "Replace",
        downloadResume: "Download resume",
        downloadError: "Could not download resume",
        resumeFallbackName: "Resume",
        additionalTitle: "Additional documents",
        additionalSectionDesc: "Transcripts, portfolios, certifications, and other files you want to reuse across applications.",
        noAdditional: "No additional documents yet",
        noAdditionalDesc: "Upload transcripts, portfolios, or certificates to attach them to your applications.",
        uploadDocument: "Upload document",
        addDocument: "Add document",
        uploadedCountOne: "1 document uploaded",
        uploadedCountMany: "{n} documents uploaded",
        uploadedOn: "Uploaded {date}",
        viewDocument: "View document",
        deleteDocument: "Delete document",
        uploadSuccess: "Document uploaded",
        uploadError: "Could not upload document",
        fileTooLarge: "File must be 10MB or smaller",
        viewError: "Could not open document",
        deleteSuccess: "Document deleted",
        deleteError: "Could not delete document",
        viewUnavailableDemo: "Document preview is unavailable in demo mode",
        configureAiSettings: "Configure AI application settings",
        configureAiSettingsHint: "Choose how AI generates your cover letter, resume, and document review for each apply.",
      },
    },
    resumeSheet: {
      uploadTitle: "Upload resume",
      updateTitle: "Update resume",
      uploadDesc: "Upload your resume to get started with personalized job applications.",
      updateDesc: "Your current resume is shown below (read-only). Upload a new file to replace it.",
      currentResume: "Current resume",
      currentOnFile: "Current resume on file",
      previewReadOnly: "Read-only preview",
      previewLoading: "Loading preview…",
      previewFrameTitle: "Resume preview",
      previewUnavailable: "Preview unavailable — download the file to view it.",
      pdfPreviewOnly: "Inline preview is available for PDF files. Upload a PDF to see it here.",
      selectFile: "Select file",
      uploading: "Uploading…",
      readyToUpload: "Ready to upload",
      uploadDocument: "Upload document",
      dropHint: "Drag and drop or click to browse",
      replaceZoneTitle: "Replace with a new file",
      fileFormats: "PDF or PNG • Max 10 MB",
      fileTypeError: "Please upload a PDF or PNG file.",
      downloadResume: "Download",
      exampleResume: "Example resume",
      exampleResumeHint: "Not sure what to upload? Here is a well-formatted entry-level resume you can use as inspiration.",
      exampleOnFile: "Sample resume for inspiration",
    },
    interviews: {
      title: "Interviews",
      subtitle: "Practise role-specific questions and get instant AI feedback.",
      streak: "Streak",
      thisWeek: "This week",
      bestScore: "Best score",
      mockTitle: "5-question mock",
      mockCta: "Start your mock interview",
      mockDesc: "Tailored to your target role. ~5 minutes. Get scored on confidence, communication, and technical answers.",
      startNow: "Start now",
      wordCount: "{count} words",
      coachTips: "Coach tips",
      likelyQuestions: "Likely questions",
      yourFeedback: "Your feedback",
      scoring: "Scoring…",
      questionOf: "Question {current} of {total}",
      interviewer: "Interviewer",
      answerPlaceholder: "Take a breath. Speak in bullets. Keep it concrete.",
      reviewing: "Reviewing your answers…",
      overall: "Overall",
      confidence: "Confidence",
      communication: "Communication",
      technical: "Technical",
      strengths: "Strengths",
      improvements: "Improvements",
      nextQuestion: "Next question",
      finishScore: "Finish & score",
      done: "Done",
      refresh: "Refresh",
      refreshing: "Refreshing…",
      scoreError: "Could not score interview",
      loadError: "Could not load coaching content",
    },
    feedback: {
      title: "Feedback",
      releaseNotes: "Release Notes",
      subtitle: "Share feedback with the founders or read release notes.",
      messagePlaceholder: "Message",
      thanks: "Thanks! Your message was sent to the team.",
      supportSoon: "Support line coming soon",
      attachmentsSoon: "Attachments coming soon",
      welcomeMessage: "What do you love/hate about {brand}? This goes directly to the founders 💬",
      callSupport: "Call support",
    },
    suggestFeature: {
      nav: "Suggest a feature",
      title: "Suggest a feature",
      subtitle: "Tell us what you'd like next, or describe a problem you ran into.",
      typeLabel: "Type",
      categoryFeature: "Feature idea",
      categoryProblem: "Problem / bug",
      categoryOther: "Other",
      detailsLabel: "Details",
      detailsPlaceholder: "Describe your idea, what you expected, or what went wrong…",
      attachmentsLabel: "Screenshots & photos",
      attachmentsHint: "Up to 5 images · PNG, JPG, WebP · 5 MB each",
      addImages: "Add",
      removeImage: "Remove image",
      send: "Send suggestion",
      sending: "Sending…",
      success: "Thanks! Your suggestion was sent to the team.",
      error: "Could not send your suggestion. Try again or email hi@hirly.com.",
      imagesOnly: "Only image files are allowed.",
      fileTooLarge: "Each image must be 5 MB or smaller.",
      sentAs: "We'll include your account email ({email}) so we can follow up.",
    },
    profileSections: {
      certifications: "Certifications",
      awards: "Awards",
      coursework: "Relevant Coursework",
      languages: "Languages",
      skills: "Skills",
      addCertifications: "Add certifications",
      addAwards: "Add awards",
      addCoursework: "Add coursework",
      addLanguages: "Add languages",
      addSkills: "Add skills",
      languagesHint: "Highlight the languages you speak and your proficiency.",
      edit: "Edit",
      jobPreferences: "Job Preferences",
      applicationDefaults: "Application Defaults",
      targetLocation: "Target location",
      locationPlaceholder: "Search for a city or country",
      phoneCountryCode: "Phone country code",
      educationSchool: "Education school",
      schoolPlaceholder: "University or school",
      degree: "Degree",
      degreePlaceholder: "Bachelor's Degree",
      fieldOfStudy: "Field of study",
      fieldPlaceholder: "Computer Science",
      graduationYear: "Graduation year",
      linkedinUrl: "LinkedIn URL",
      websitePortfolio: "Website or portfolio",
      currentCountry: "Current country",
      countryPlaceholder: "United Kingdom",
      currentCity: "Current city",
      cityPlaceholder: "London",
      workAuthorized: "Work-authorized countries",
      workAuthorizedPlaceholder: "United Kingdom, United States",
      referralSource: "Default referral source",
      referralPlaceholder: "Hirly",
      dismiss: "Dismiss",
      settings: "Settings",
    },
    upgrade: {
      title: "Unlock Your Dream Career",
      subtitle: "Join thousands who landed their dream jobs with Hirly",
      limitedOffer: "Limited Time Offer",
      save25: "Save 25%",
      monthly: "Monthly",
      weekly: "Weekly",
      popular: "POPULAR",
      perMonth: "/ mo",
      perWeek: "/ wk",
      applications: "{n} apps",
      cta: "Start Growing with Hirly",
      cancelAnytime: "Cancel anytime",
      securePayments: "Secure payments",
      instantAccess: "Instant access",
      terms: "Terms of Use",
      privacy: "Privacy Policy",
      stripe: "Secure checkout powered by Stripe",
      checkoutError: "Could not start checkout. Please try again.",
      checkoutFailed: "Checkout failed. Please try again.",
      checkoutCancelled: "Checkout cancelled",
      checkoutSuccess: "Payment received",
      featureSwipeTitle: "Swipe to Apply",
      featureSwipeDesc: "Apply to hundreds of jobs with just a swipe — no more tedious forms.",
      featureResumeTitle: "AI-Generated Resumes",
      featureResumeDesc: "Automatically create tailored resumes for each job application.",
      featureCoverTitle: "AI Cover Letters",
      featureCoverDesc: "Personalized cover letters written by AI for every application.",
      featureMatchTitle: "Smart Job Matching",
      featureMatchDesc: "AI learns your preferences to show you the perfect opportunities.",
      statDownloads: "Downloads",
      statJobs: "Jobs Available",
      statRating: "Rating",
      benefitTimingTitle: "Perfect timing advantage",
      benefitTimingDesc: "Job postings are fresh — apply before competition floods in.",
      benefitInstantTitle: "Instant application power",
      benefitInstantDesc: "Credits activate immediately — no waiting, no delays.",
      benefitAiTitle: "AI-powered precision",
      benefitAiDesc: "Every application is tailored for maximum impact.",
      benefitSuccessTitle: "Higher success rate",
      benefitSuccessDesc: "More applications mean more interviews and better odds.",
    },
    toasts: {
      generatingApp: "Generating tailored application…",
      generatingAppDesc: "This can take up to a minute for detailed job posts.",
      demoApplying: "Saving application…",
      searchUpdated: "Search updated",
      searchSaveError: "Could not save search preferences",
      undone: "Undone",
      nothingToUndo: "Nothing to undo",
      linkCopied: "Link copied to clipboard",
      shareError: "Could not share this job",
      reportThanks: "Thanks — we'll review this listing",
      swipeFailed: "Swipe failed",
      loadJobsError: "Failed to load jobs",
    },
  },
  fr: {
    common: {
      back: "Retour",
      cancel: "Annuler",
      save: "Enregistrer",
      add: "Ajouter",
      clear: "Effacer",
      refresh: "Actualiser le feed",
      loading: "Chargement…",
      notSet: "Non renseigné",
      yes: "Oui",
      no: "Non",
      account: "Compte",
      platform: "Plateforme",
      support: "Support",
      credits: "Crédits",
      unlimited: "Illimité",
      language: "Langue",
      english: "Anglais",
      french: "Français",
    },
    accountMenu: {
      account: "Compte",
      billing: "Facturation",
      logOut: "Se déconnecter",
    },
    billingPage: {
      title: "Facturation & abonnement",
      currentSubscription: "Abonnement actuel",
      currentSubscriptionDesc: "Abonnez-vous pour débloquer les fonctionnalités premium et les candidatures illimitées.",
      noSubscription: "Aucun abonnement actif",
      noSubscriptionDesc: "Abonnez-vous pour accéder aux fonctionnalités premium, CV IA et candidatures illimitées.",
      viewPlans: "Voir les offres & s'abonner",
      manageSubscription: "Gérer l'abonnement",
      premiumActive: "Premium actif",
      premiumActiveDesc: "Votre abonnement est actif. Gérez la facturation dans le portail client.",
      mobileSubscriptionTitle: "Abonnement mobile ?",
      mobileSubscriptionDesc: "Si vous avez acheté un abonnement via l'app mobile, liez votre compte pour le gérer ici.",
      linkMobilePurchase: "Lier un achat mobile",
      usageCredits: "Utilisation & crédits",
      usageCreditsDesc: "Suivez votre consommation de crédits et le solde restant pour cette période.",
      currentCreditPeriod: "Période de crédits en cours",
      creditsUsed: "Crédits utilisés",
      creditsOf: "{used} sur {total} crédits",
      usedThisPeriod: "utilisés cette période",
      usageProgress: "Progression",
      remaining: "{n} restants",
      getMoreCredits: "Obtenir plus de crédits",
      getMoreCreditsDesc: "Abonnez-vous pour obtenir plus de crédits pour votre recherche",
      subscribeNow: "S'abonner",
      dailyUsage: "Utilisation quotidienne",
      daysShown: "{n} jours affichés",
      past7Days: "7 derniers jours",
      past14Days: "14 derniers jours",
      past30Days: "30 derniers jours",
      applications: "Candidatures",
    },
    nav: {
      feed: "Feed",
      jobs: "Offres",
      review: "Relecture",
      applications: "Candidatures",
      inbox: "Messages",
      profile: "Profil",
      aiSettings: "Réglages IA",
    },
    swipe: {
      pass: "Passer",
      apply: "Postuler",
      passStamp: "PASS",
      skipStamp: "PASS",
      applyStamp: "POSTULER",
      tapForDetails: "Appuyer pour les détails",
      tapToFlipBack: "Appuyer pour revenir",
      swipeHint: "Swipe ou appui · Appuyer sur la carte pour les détails",
      jobTitle: "Intitulé du poste",
      location: "Lieu",
      postedToday: "Publié aujourd'hui",
      postedOneDay: "Publié il y a 1 jour",
      postedDays: "Publié il y a {n} jours",
      postedRecently: "Publié récemment",
      locationNotSpecified: "Lieu non précisé",
      aboutRole: "À propos du poste",
      whyFits: "Pourquoi ce poste vous convient",
      requiredQualifications: "Qualifications requises",
      techStack: "Stack technique",
      noJobs: "Aucune offre trouvée",
      noJobsFilters: "Aucune offre en un swipe avec ces filtres.",
      couldNotLoad: "Impossible de charger les offres.",
      setTargetRole: "Définir le poste cible",
      anywhere: "Partout",
      tapToEdit: "appuyer pour modifier",
      openFilters: "Ouvrir les filtres",
      undoSwipe: "Annuler le dernier swipe",
      history: "Historique",
      reportJob: "Signaler l'offre",
      shareJob: "Partager l'offre",
      entryLevel: "Junior",
      midLevel: "Intermédiaire",
      senior: "Senior",
      lead: "Lead",
      principal: "Principal",
      fullTime: "Temps plein",
      remote: "Télétravail",
      hybrid: "Hybride",
      inPerson: "Sur site",
      switchLight: "Passer en mode clair",
      switchDark: "Passer en mode sombre",
      notifications: "Notifications",
      feedTimeout: "Le chargement des offres prend trop de temps. Actualisez ou élargissez vos filtres.",
      providerRateLimited: "Le fournisseur d'offres est temporairement limité. Réessayez plus tard ou élargissez les filtres.",
      widenFiltersHint: "Élargissez la distance, ajoutez des lieux ou choisissez un autre poste.",
      tryWidenSearch: "Élargissez la zone de recherche ou changez de lieu.",
      editTarget: "Modifier le poste et le lieu cibles",
      swipeReadyReview: "Prêt pour relecture",
      swipeAppPrepared: "Candidature préparée",
      swipeWaitingReview: "{company} attend dans Relecture. Approuvez les documents pour envoyer.",
      swipeReadyApps: "{company} est prêt dans Candidatures. Pas encore envoyé.",
      swipeActionRequiredDesc: "Ouvrez Candidatures pour répondre aux questions restantes.",
      swipeHumanVerification: "Vérification humaine requise",
      swipeHumanVerificationDesc: "Ouvrez Candidatures pour terminer la vérification manuelle.",
      swipePackageGenerated: "Dossier de candidature généré",
      swipePackageFailed: "La préparation navigateur a échoué. Réessayez depuis Candidatures.",
      swipeTextGenerated: "Texte de candidature généré",
      swipeTextGeneratedDesc: "CV et lettre prêts, mais le dossier fichier nécessite une relecture.",
      swipeMoreProfile: "Plus de données profil nécessaires",
      swipeMoreProfileDesc: "Complétez votre CV/profil pour une candidature plus solide.",
      swipeMoreJob: "Plus de données sur l'offre nécessaires",
      swipeMoreJobDesc: "Cette annonce ne contient pas assez de détails pour un dossier sur mesure.",
      swipeAppSaved: "Candidature enregistrée",
      swipeAppSavedDesc: "La génération a échoué. Consultez Candidatures pour relire ou réessayer.",
      swipePackageFor: "Dossier généré pour {company}",
      swipePackageReady: "CV et lettre prêts. Pas encore envoyés.",
      demoApplied: "Candidature enregistrée (démo)",
      demoAppliedDesc: "Mode démo — candidature sauvegardée en local. Rien n'a été envoyé à l'entreprise.",
      generationTimeout: "La génération prend plus de temps que prévu. Consultez Candidatures dans un instant.",
      noJobsFiltered: "Aucune offre avec ces filtres.",
      industryProductDesign: "Design produit",
      industryInfrastructure: "Infrastructure",
      industryAiMl: "IA / ML",
      industryMarketing: "Marketing",
      industryTechnology: "Technologie",
      companySize11: "11-50 employés",
      companySize51: "51-500 employés",
      companySize501: "501-1000 employés",
      companySize1001: "1001-5000 employés",
    },
    filters: {
      title: "Filtres",
      postedDate: "Date de publication",
      workLocation: "Mode de travail",
      experience: "Expérience",
      jobType: "Type de contrat",
      salary: "Salaire",
      company: "Entreprise",
      industry: "Secteur",
      includeUnknownLocation: "Inclure les lieux non précisés",
      includeUnknownSalary: "Inclure les salaires non précisés",
      minimum: "Minimum :",
      onlyCompanies: "Afficher uniquement",
      hideCompanies: "Masquer les offres de",
      onlyIndustries: "Afficher uniquement les secteurs",
      hideIndustries: "Masquer les secteurs",
      companyPlaceholder: "Nom de l'entreprise",
      industryPlaceholder: "Nom du secteur",
      removeValue: "Retirer {value}",
      clear: "Effacer les filtres",
      dateAny: "Toutes dates",
      date1d: "24 dernières heures",
      date7d: "Semaine passée",
      date30d: "Mois passé",
      workOnsite: "Sur site",
      workHybrid: "Hybride",
      workRemote: "Télétravail",
      jobFullTime: "CDI / Temps plein",
      jobPartTime: "Temps partiel",
      jobInternship: "Stage",
      jobFixedTerm: "CDD",
      jobApprenticeship: "Alternance",
      jobSummer: "Job d'été",
      jobSeasonal: "Saisonnier",
      jobFreelance: "Freelance",
      expEntry: "Junior",
      expMid: "Intermédiaire",
      expSenior: "Senior",
      expExecutive: "Direction",
    },
    settings: {
      title: "Réglages",
      lookAndFeel: "Apparence",
      theme: "Thème",
      alerts: "Alertes",
      notificationPrefs: "Préférences de notification",
      walkthrough: "Visite guidée",
      replayWalkthrough: "Rejouer la visite",
      privacyData: "Confidentialité & données",
      privacyPolicy: "Politique de confidentialité",
      termsOfUse: "Conditions d'utilisation",
      planHelp: "Offre & aide",
      manageBilling: "Gérer la facturation",
      upgradePlan: "Passer au premium",
      restorePurchase: "Restaurer l'achat",
      talkToUs: "Nous contacter",
      shareBrand: "Partager {brand}",
      inviteFriend: "Inviter un ami",
      onInstagram: "Nous sur Instagram",
      onTikTok: "Nous sur TikTok",
      yourAccount: "Votre compte",
      signOut: "Se déconnecter",
      deleteAccount: "Supprimer le compte",
      userId: "ID utilisateur",
      comingSoon: "{feature} — bientôt disponible",
      inviteCopied: "Lien d'invitation copié",
      billingPortalError: "Impossible d'ouvrir le portail de facturation",
      deleteConfirm: "Supprimer votre compte Hirly ? Votre profil, swipes et candidatures seront effacés. Action irréversible.",
      accountDeleted: "Compte supprimé",
      deleteError: "Impossible de supprimer le compte",
      languageTitle: "Langue de l'app",
      languageDesc: "Langue des menus, boutons et fiches offres.",
      languageSetEn: "Langue définie sur l'anglais",
      languageSetFr: "Langue définie sur le français",
    },
    aiSettings: {
      poweredBy: "Propulsé par l'IA {brand}",
      title: "Réglages IA",
      subtitle: "Réglages des candidatures IA",
      description: "Choisissez comment l'IA vous aide — rapidité, qualité et contrôle au même endroit.",
      featuresOn: "{n}/4 fonctionnalités actives",
      swipeReady: "Candidature en 1 swipe prête",
      promoTitle: "Pensé pour les démos",
      promoBody: "Interface claire · bascules instantanées · rendu pro",
      automation: "Automatisation",
      coverLetter: "Lettre de motivation IA",
      coverLetterDesc: "Génère une lettre adaptée à chaque candidature",
      coverLetterStat: "~90 s gagnées",
      resume: "CV IA",
      resumeDesc: "Génère un CV adapté à chaque candidature",
      resumeStat: "Optimisé ATS",
      reviewDocs: "Relecture des documents",
      reviewDocsDesc: "Validez les documents générés avant qu'ils soient utilisés",
      reviewDocsStat: "Contrôle total",
      findGaps: "Trouver les lacunes du CV",
      findGapsDesc: "Répondez aux exigences du poste pour améliorer CV et lettre",
      findGapsStat: "Meilleurs matchs",
      mobileIntro: "Choisissez comment l'IA assiste vos candidatures.",
    },
    demoSettings: {
      sectionTitle: "Mode démo",
      sectionIntro: "Offres finance à Paris pour enregistrements d'écran et démos produit.",
      financeJobFeed: "Offres finance (Paris)",
      financeJobFeedDesc: "Remplace le feed live par 30 postes banque & marchés (BNP, SocGen, Natixis…). Candidatures locales uniquement.",
      financeJobFeedOn: "Feed démo finance activé",
      financeJobFeedOff: "Feed démo finance désactivé",
    },
    demo: {
      badge: "Compte démo",
      banner: "Les candidatures restent locales pour les enregistrements d'écran. Rien n'est envoyé aux employeurs.",
    },
    credits: {
      viewPlans: "Voir les offres",
      unlimitedAria: "Crédits illimités",
    },
    review: {
      title: "Relecture",
      subtitleOn: "Approuvez les documents avant envoi.",
      subtitleOff: "Activez Relecture des documents dans les Réglages IA.",
      disabledTitle: "Relecture désactivée",
      openAiSettings: "Ouvrir les Réglages IA",
      allCaughtUp: "Tout est à jour",
      backToJobs: "Retour aux offres",
      readyToReview: "Prêt à relire",
      generatedRecently: "Généré récemment",
      generatedOn: "Généré le {date}",
      dialogHint: "Relisez le CV et la lettre ci-dessous. Approuvez pour envoyer la candidature.",
      cv: "CV",
      coverLetter: "Lettre",
      approveSubmit: "Approuver & envoyer",
      loadError: "Impossible de charger les candidatures",
      openError: "Impossible d'ouvrir la candidature",
      submitted: "Candidature envoyée",
      actionRequired: "Action requise",
      approved: "Candidature approuvée",
      submitError: "Impossible d'envoyer la candidature",
      disabledBody: "Les candidatures sont préparées automatiquement quand vous swipez à droite. Activez Relecture des documents pour approuver chaque dossier avant envoi.",
      emptyBody: "Aucune candidature n'attend votre relecture. Swipez à droite pour générer de nouveaux dossiers.",
      approvedDesc: "Nous finalisons l'envoi.",
      actionRequiredDesc: "Quelques réponses sont nécessaires avant de terminer.",
    },
    tracker: {
      title: "Candidatures",
      subtitle: "Suivez dossiers, envois et relances au même endroit.",
      addResume: "Ajoutez votre CV",
      addResumeBody: "Importez votre CV principal pour activer les candidatures et le suivi.",
      uploadResume: "Importer le CV",
      yourApplications: "Vos candidatures",
      summary: "Résumé",
      nextAction: "Prochaine action",
      generatedDocs: "Documents générés",
      timeline: "Chronologie",
      whyFit: "Pourquoi ce poste",
      searchPlaceholder: "Rechercher entreprise, poste ou lieu",
      nothingYet: "Rien pour l'instant",
      noSearchMatch: "Aucune candidature ne correspond.",
      backToSwipe: "Retour au swipe",
      totalApplications: "Total candidatures",
      successRate: "Taux de succès",
      pending: "En attente",
      actionRequired: "Action requise",
      all: "Tout",
      prepared: "Préparé",
      ready: "Prêt",
      submitted: "Envoyé",
      applied: "Postulé",
      failed: "Échec",
      expired: "Expiré",
      untitledRole: "Poste sans titre",
      unknownCompany: "Entreprise inconnue",
      securityCheck: "Vérification de sécurité",
      needsAttention: "Attention requise",
      appPending: "Candidature en attente",
      answerQuestions: "Répondre aux questions",
      viewIssue: "Voir le problème",
      finalizing: "Finalisation",
      generated: "Généré",
      today: "Aujourd'hui",
      yesterday: "Hier",
      daysAgo: "Il y a {n} jours",
      oneWeekAgo: "Il y a 1 sem.",
      weeksAgo: "Il y a {n} sem.",
      atsUnknown: "ATS inconnu",
      emptyAll: "Aucune candidature. Swipez à droite pour commencer le suivi ici.",
      emptyActionRequired: "Aucune candidature ne nécessite de réponses pour l'instant.",
      emptyPending: "Aucune candidature en attente pour l'instant.",
      emptySubmitted: "Aucune candidature envoyée pour l'instant.",
      emptyPrepared: "Aucune candidature préparée pour l'instant.",
      emptyFailed: "Aucune candidature en échec pour l'instant.",
      emptyExpired: "Aucune candidature expirée.",
      emptyDefault: "Aucune candidature trouvée.",
      timelineCreated: "Candidature créée",
      timelinePackage: "Dossier sur mesure généré",
      timelineSubmitted: "Candidature envoyée",
      timelineAnswersNeeded: "Réponses nécessaires",
      timelinePending: "Candidature en attente",
      timelinePrepared: "Candidature préparée",
      timelineSecurity: "Vérification de sécurité",
      timelineFailed: "Attention requise",
      timelineExpired: "Candidature expirée",
      statusSubmitted: "Envoyé",
      statusFinalizing: "Nous finalisons votre candidature.",
      statusPrepared: "Candidature préparée. L'envoi final n'est pas encore activé.",
      statusBlocked: "Quelques réponses sont nécessaires avant de préparer cette candidature.",
      statusCaptcha: "Une vérification de sécurité supplémentaire est requise.",
      statusPrepareFailed: "Dossier généré, mais la préparation navigateur a échoué.",
      statusFailed: "Échec de l'envoi.",
      statusUnknown: "Statut d'envoi inconnu. Vérifiez avant de continuer.",
      statusNotSubmitted: "Pas encore envoyé",
      cvDownloaded: "CV téléchargé",
      coverDownloaded: "Lettre téléchargée",
      submittedCount: "{n} envoyées",
      submittedOverTotal: "envoyées / total",
      beingFinalized: "en finalisation",
      needAttentionCount: "{n} nécessitent attention",
      locationNotListed: "Lieu non indiqué",
      recently: "récemment",
      updated: "Mis à jour {date}",
      applied: "Postulé {date}",
      available: "Disponible",
      skippedJobs: "Offres passées",
      listApplying: "Envoi en cours…",
      listViewApplication: "Voir la candidature",
      listViewPackage: "Voir le dossier",
      listAnswerQuestions: "Répondre aux questions",
      listSecurityCheck: "Vérification",
      listViewDetails: "Voir les détails",
    },
    history: {
      generated: "Générés",
      passed: "Passés",
      passedTitle: "Offres passées",
      generatedTitle: "Dossiers générés",
      subtitle: "Consultez les dossiers générés et les offres passées.",
      generatePackage: "Générer un dossier",
      noPassed: "Aucune offre passée pour l'instant.",
      noGenerated: "Aucun dossier généré pour l'instant.",
      loadError: "Impossible de charger l'historique",
      packageGenerated: "Dossier généré. Pas encore envoyé.",
      packageError: "Impossible de générer le dossier. Réessayez.",
    },
    emails: {
      searchMail: "Rechercher dans les mails",
      primary: "Principal",
      verification: "Vérification",
      interview: "Entretien",
      offer: "Offre",
      inboxTitle: "Boîte mail",
      inboxSubtitle: "Invitations, offres et mises à jour de candidatures.",
      emptyFolder: "Aucun message dans ce dossier.",
      newOutreach: "Nouvel e-mail de prospection",
      emailType: "Type d'e-mail",
      application: "Candidature",
      preview: "Aperçu",
      generate: "Générer",
      copySaveDraft: "Copier & enregistrer brouillon",
      saved: "Enregistré",
      noDrafts: "Aucun brouillon. Générez un e-mail pour en créer un.",
      connectGmail: "Connecter Gmail",
      syncInbox: "Synchronisez votre boîte pour voir les réponses.",
      comingSoon: "Bientôt disponible",
      reply: "Répondre",
      archive: "Archiver",
      markUnread: "Marquer non lu",
      more: "Plus",
      back: "Retour",
      toMe: "à moi",
      writeReply: "Écrivez votre réponse…",
      send: "Envoyer",
      copiedDraft: "Copié et enregistré en brouillon",
      writeReplyFirst: "Écrivez d'abord une réponse",
      cantReply: "Impossible de répondre à ce message",
      markedUnread: "Marqué comme non lu",
      archived: "Message archivé",
      reportThanks: "Signalement envoyé — merci",
      replySent: "Réponse envoyée",
      copied: "Copié dans le presse-papiers",
      draftDeleted: "Brouillon supprimé",
      sent: "Envoyé",
      replied: "Répondu",
      composeEmail: "Rédiger un e-mail",
      system: "Système",
      copy: "Copier",
      addedStarred: "Ajouté aux favoris",
      removedStarred: "Retiré des favoris",
    },
    profile: {
      title: "Profil",
      subtitle: "CV, infos personnelles et valeurs par défaut.",
      resume: "CV",
      personal: "Infos perso",
      files: "Fichiers",
      documentsTab: "Documents",
      yourCv: "Votre CV",
      resumeUploaded: "CV importé — appuyer pour mettre à jour",
      uploadResume: "Importer votre CV",
      completeProfile: "Complétez votre profil",
      completeProfileBody: "Préremplissez plus de champs de candidature.",
      finishProfile: "Terminer le profil",
      upgradePlan: "Passer au premium",
      unlimitedSwipes: "Swipes illimités",
      creditsRemaining: "Crédits de candidature restants",
      jobPreferences: "Préférences emploi",
      targetLocation: "Lieu cible",
      remotePreference: "Préférence télétravail",
      seniority: "Séniorité",
      applicationDefaults: "Valeurs par défaut",
      personalDetails: "Informations personnelles",
      addYourName: "Ajoutez votre nom",
      otherFiles: "Autres fichiers",
      otherFilesHint: "Relevés de notes, portfolios, certificats…",
      preferencesSaved: "Préférences enregistrées",
      preferencesError: "Impossible d'enregistrer les préférences",
      defaultsSaved: "Valeurs par défaut enregistrées",
      defaultsError: "Impossible d'enregistrer les valeurs par défaut",
      selectLocation: "Choisissez un lieu dans les suggestions",
      extractedData: "Données de candidature extraites",
      extractedDataHint: "Détails CV réutilisables pour les formulaires",
      applicationDefaultsHint: "Réponses réutilisables pour les candidatures en 1 swipe",
      any: "Tout",
      remoteOnly: "Télétravail uniquement",
      onsite: "Sur site",
      personalInfo: {
        contactTitle: "Coordonnées",
        contactDesc: "Vos informations de contact pour les candidatures et échanges professionnels.",
        salaryTitle: "Prétentions salariales",
        salaryDesc: "Indiquez votre fourchette salariale pour mieux cibler les offres adaptées.",
        demographicsTitle: "Informations démographiques",
        demographicsDesc: "Aidez-nous à mieux comprendre votre profil pour une expérience plus pertinente.",
        firstName: "Prénom",
        lastName: "Nom",
        email: "E-mail",
        phone: "Téléphone",
        address: "Adresse",
        minimum: "Minimum",
        maximum: "Maximum",
        salarySummary: "Recherche de postes entre {min} et {max} par an",
        dateOfBirth: "Date de naissance",
        gender: "Genre",
        ethnicity: "Origine ethnique",
        disabilityStatus: "Statut handicap",
        sexualOrientation: "Orientation sexuelle",
        veteranStatus: "Statut vétéran",
        citizenshipStatus: "Statut de citoyenneté",
        selectGender: "Choisir le genre",
        selectStatus: "Choisir le statut",
        selectOrientation: "Choisir l'orientation",
        editAddress: "Modifier l'adresse",
        clearAddress: "Effacer l'adresse",
        addCitizenship: "Ajouter un statut de citoyenneté",
        citizenshipCountry: "Pays ou région",
        citizenshipType: "Type de statut",
        removeCitizenship: "Supprimer l'entrée",
        noCitizenship: "Aucun statut de citoyenneté",
        noCitizenshipDesc: "Ajoutez votre citoyenneté ou statut de visa pour clarifier votre autorisation de travail.",
        contactSaved: "Coordonnées enregistrées",
        salarySaved: "Prétentions salariales enregistrées",
        demographicsSaved: "Informations démographiques enregistrées",
        saveError: "Impossible d'enregistrer les modifications",
      },
      documents: {
        resumeTitle: "CV",
        resumeSectionDesc: "Votre CV principal pour construire votre profil et générer des candidatures sur mesure.",
        noResume: "Aucun CV importé",
        noResumeDesc: "Importez votre CV pour construire votre profil professionnel et générer des candidatures sur mesure.",
        uploadResume: "Importer CV",
        resumeOnFile: "CV actuel enregistré",
        replaceResume: "Remplacer",
        downloadResume: "Télécharger le CV",
        downloadError: "Impossible de télécharger le CV",
        resumeFallbackName: "CV",
        additionalTitle: "Documents additionnels",
        additionalSectionDesc: "Relevés de notes, portfolios, certifications et autres fichiers réutilisables.",
        noAdditional: "Aucun document additionnel",
        noAdditionalDesc: "Importez des relevés, portfolios ou certificats à joindre à vos candidatures.",
        uploadDocument: "Importer",
        addDocument: "Ajouter un document",
        uploadedCountOne: "1 document importé",
        uploadedCountMany: "{n} documents importés",
        uploadedOn: "Importé le {date}",
        viewDocument: "Voir le document",
        deleteDocument: "Supprimer le document",
        uploadSuccess: "Document importé",
        uploadError: "Impossible d'importer le document",
        fileTooLarge: "Le fichier doit faire 10 Mo ou moins",
        viewError: "Impossible d'ouvrir le document",
        deleteSuccess: "Document supprimé",
        deleteError: "Impossible de supprimer le document",
        viewUnavailableDemo: "Aperçu indisponible en mode démo",
        configureAiSettings: "Réglages candidature IA",
        configureAiSettingsHint: "Choisissez comment l'IA génère la lettre, le CV et la relecture pour chaque candidature.",
      },
    },
    resumeSheet: {
      uploadTitle: "Importer un CV",
      updateTitle: "Mettre à jour le CV",
      uploadDesc: "Importez votre CV pour démarrer des candidatures personnalisées.",
      updateDesc: "Votre CV actuel s'affiche ci-dessous (lecture seule). Importez un nouveau fichier pour le remplacer.",
      currentResume: "CV actuel",
      currentOnFile: "CV enregistré",
      previewReadOnly: "Aperçu en lecture seule",
      previewLoading: "Chargement de l'aperçu…",
      previewFrameTitle: "Aperçu du CV",
      previewUnavailable: "Aperçu indisponible — téléchargez le fichier pour le consulter.",
      pdfPreviewOnly: "L'aperçu intégré est disponible pour les PDF. Importez un PDF pour l'afficher ici.",
      selectFile: "Choisir un fichier",
      uploading: "Import en cours…",
      readyToUpload: "Prêt à importer",
      uploadDocument: "Importer un document",
      dropHint: "Glissez-déposez ou cliquez pour parcourir",
      replaceZoneTitle: "Remplacer par un nouveau fichier",
      fileFormats: "PDF ou PNG • 10 Mo max",
      fileTypeError: "Importez un fichier PDF ou PNG.",
      downloadResume: "Télécharger",
      exampleResume: "CV exemple",
      exampleResumeHint: "Pas sûr de quoi importer ? Voici un CV débutant bien formaté pour vous inspirer.",
      exampleOnFile: "CV exemple à titre indicatif",
    },
    interviews: {
      title: "Entretiens",
      subtitle: "Entraînez-vous avec des questions ciblées et un feedback IA instantané.",
      streak: "Série",
      thisWeek: "Cette semaine",
      bestScore: "Meilleur score",
      mockTitle: "Mock 5 questions",
      mockCta: "Lancer votre entretien blanc",
      mockDesc: "Adapté à votre poste cible. ~5 minutes. Évaluez confiance, communication et réponses techniques.",
      startNow: "Commencer",
      wordCount: "{count} mots",
      coachTips: "Conseils coach",
      likelyQuestions: "Questions probables",
      yourFeedback: "Votre feedback",
      scoring: "Notation…",
      questionOf: "Question {current} sur {total}",
      interviewer: "Recruteur",
      answerPlaceholder: "Respirez. Répondez en points. Restez concret.",
      reviewing: "Analyse de vos réponses…",
      overall: "Global",
      confidence: "Confiance",
      communication: "Communication",
      technical: "Technique",
      strengths: "Points forts",
      improvements: "Axes d'amélioration",
      nextQuestion: "Question suivante",
      finishScore: "Terminer & noter",
      done: "Terminé",
      refresh: "Actualiser",
      refreshing: "Actualisation…",
      scoreError: "Impossible de noter l'entretien",
      loadError: "Impossible de charger le contenu coach",
    },
    feedback: {
      title: "Feedback",
      releaseNotes: "Notes de version",
      subtitle: "Partagez un retour avec les fondateurs ou lisez les notes de version.",
      messagePlaceholder: "Message",
      thanks: "Merci ! Votre message a été envoyé à l'équipe.",
      supportSoon: "Support bientôt disponible",
      attachmentsSoon: "Pièces jointes bientôt disponibles",
      welcomeMessage: "Qu'aimez-vous/détestez-vous chez {brand} ? Cela va directement aux fondateurs 💬",
      callSupport: "Appeler le support",
    },
    suggestFeature: {
      nav: "Suggérer une fonctionnalité",
      title: "Suggérer une fonctionnalité",
      subtitle: "Dis-nous ce que tu voudrais en plus, ou décris un problème rencontré.",
      typeLabel: "Type",
      categoryFeature: "Idée de feature",
      categoryProblem: "Problème / bug",
      categoryOther: "Autre",
      detailsLabel: "Détails",
      detailsPlaceholder: "Décris ton idée, ce que tu attendais, ou ce qui s'est passé…",
      attachmentsLabel: "Captures & photos",
      attachmentsHint: "Jusqu'à 5 images · PNG, JPG, WebP · 5 Mo max chacune",
      addImages: "Ajouter",
      removeImage: "Retirer l'image",
      send: "Envoyer",
      sending: "Envoi…",
      success: "Merci ! Ta suggestion a été envoyée à l'équipe.",
      error: "Impossible d'envoyer ta suggestion. Réessaie ou écris à hi@hirly.com.",
      imagesOnly: "Seules les images sont acceptées.",
      fileTooLarge: "Chaque image doit faire 5 Mo maximum.",
      sentAs: "On inclura ton e-mail de compte ({email}) pour te recontacter.",
    },
    profileSections: {
      certifications: "Certifications",
      awards: "Distinctions",
      coursework: "Cours pertinents",
      languages: "Langues",
      skills: "Compétences",
      addCertifications: "Ajouter des certifications",
      addAwards: "Ajouter des distinctions",
      addCoursework: "Ajouter des cours",
      addLanguages: "Ajouter des langues",
      addSkills: "Ajouter des compétences",
      languagesHint: "Indiquez les langues parlées et votre niveau.",
      edit: "Modifier",
      jobPreferences: "Préférences emploi",
      applicationDefaults: "Valeurs par défaut",
      targetLocation: "Lieu cible",
      locationPlaceholder: "Rechercher une ville ou un pays",
      phoneCountryCode: "Indicatif téléphonique",
      educationSchool: "Établissement",
      schoolPlaceholder: "Université ou école",
      degree: "Diplôme",
      degreePlaceholder: "Licence",
      fieldOfStudy: "Domaine d'études",
      fieldPlaceholder: "Informatique",
      graduationYear: "Année de diplôme",
      linkedinUrl: "URL LinkedIn",
      websitePortfolio: "Site ou portfolio",
      currentCountry: "Pays actuel",
      countryPlaceholder: "Royaume-Uni",
      currentCity: "Ville actuelle",
      cityPlaceholder: "Londres",
      workAuthorized: "Pays d'autorisation de travail",
      workAuthorizedPlaceholder: "Royaume-Uni, États-Unis",
      referralSource: "Source de recommandation par défaut",
      referralPlaceholder: "Hirly",
      dismiss: "Fermer",
      settings: "Réglages",
    },
    upgrade: {
      title: "Débloquez la carrière de vos rêves",
      subtitle: "Rejoignez ceux qui ont décroché leur job idéal avec Hirly",
      limitedOffer: "Offre limitée",
      save25: "-25 %",
      monthly: "Mensuel",
      weekly: "Hebdo",
      popular: "POPULAIRE",
      perMonth: "/ mois",
      perWeek: "/ sem.",
      applications: "{n} candid.",
      cta: "Décrocher mon prochain job",
      cancelAnytime: "Sans engagement",
      securePayments: "Paiement sécurisé",
      instantAccess: "Accès immédiat",
      terms: "Conditions",
      privacy: "Confidentialité",
      stripe: "Paiement sécurisé via Stripe",
      checkoutError: "Impossible de lancer le paiement. Réessayez.",
      checkoutFailed: "Échec du paiement. Réessayez.",
      checkoutCancelled: "Paiement annulé",
      checkoutSuccess: "Paiement reçu",
      featureSwipeTitle: "Swipe pour postuler",
      featureSwipeDesc: "Postulez à des centaines d'offres en un swipe — fini les formulaires.",
      featureResumeTitle: "CV générés par IA",
      featureResumeDesc: "Créez automatiquement un CV adapté à chaque candidature.",
      featureCoverTitle: "Lettres IA",
      featureCoverDesc: "Des lettres personnalisées par l'IA pour chaque candidature.",
      featureMatchTitle: "Matching intelligent",
      featureMatchDesc: "L'IA apprend vos préférences pour vous montrer les bonnes offres.",
      statDownloads: "Downloads",
      statJobs: "Offres",
      statRating: "Note",
      benefitTimingTitle: "Timing parfait",
      benefitTimingDesc: "Les offres sont fraîches — postulez avant la concurrence.",
      benefitInstantTitle: "Puissance instantanée",
      benefitInstantDesc: "Les crédits s'activent immédiatement — sans attente.",
      benefitAiTitle: "Précision IA",
      benefitAiDesc: "Chaque candidature est adaptée pour maximiser l'impact.",
      benefitSuccessTitle: "Meilleur taux de succès",
      benefitSuccessDesc: "Plus de candidatures = plus d'entretiens.",
    },
    toasts: {
      generatingApp: "Génération de la candidature…",
      generatingAppDesc: "Cela peut prendre jusqu'à une minute pour les offres détaillées.",
      demoApplying: "Enregistrement de la candidature…",
      searchUpdated: "Recherche mise à jour",
      searchSaveError: "Impossible d'enregistrer la recherche",
      undone: "Annulé",
      nothingToUndo: "Rien à annuler",
      linkCopied: "Lien copié",
      shareError: "Impossible de partager cette offre",
      reportThanks: "Merci — nous allons examiner cette annonce",
      swipeFailed: "Échec du swipe",
      loadJobsError: "Impossible de charger les offres",
    },
  },
};

export function appT(lang, key, vars = {}) {
  const parts = key.split(".");
  let cur = APP_UI[lang] || APP_UI.en;
  for (const part of parts) {
    cur = cur?.[part];
  }
  if (typeof cur !== "string") return key;
  return Object.entries(vars).reduce(
    (text, [k, v]) => text.replace(new RegExp(`\\{${k}\\}`, "g"), String(v)),
    cur,
  );
}

export function readStoredAppLang() {
  if (typeof window === "undefined") return "fr";
  try {
    const stored = localStorage.getItem("hirly_app_lang");
    if (stored === "en" || stored === "fr") return stored;
    return "fr";
  } catch (_) {
    return "fr";
  }
}

export function getFilterPanels(t) {
  return [
    { id: "postedDate", label: t("filters.postedDate") },
    { id: "workLocation", label: t("filters.workLocation") },
    { id: "experience", label: t("filters.experience") },
    { id: "jobType", label: t("filters.jobType") },
    { id: "salary", label: t("filters.salary") },
    { id: "company", label: t("filters.company") },
    { id: "industry", label: t("filters.industry") },
  ];
}

export function getDateOptions(t) {
  return [
    { value: "any", label: t("filters.dateAny") },
    { value: "1d", label: t("filters.date1d") },
    { value: "7d", label: t("filters.date7d") },
    { value: "30d", label: t("filters.date30d") },
  ];
}

export function getWorkLocationOptions(t) {
  return [
    { value: "onsite", label: t("filters.workOnsite") },
    { value: "hybrid", label: t("filters.workHybrid") },
    { value: "remote", label: t("filters.workRemote") },
  ];
}

export function getJobTypeOptions(t) {
  return [
    { value: "full_time", label: t("filters.jobFullTime") },
    { value: "part_time", label: t("filters.jobPartTime") },
    { value: "internship", label: t("filters.jobInternship") },
    { value: "fixed_term", label: t("filters.jobFixedTerm") },
    { value: "apprenticeship", label: t("filters.jobApprenticeship") },
    { value: "summer_job", label: t("filters.jobSummer") },
    { value: "seasonal", label: t("filters.jobSeasonal") },
    { value: "freelance", label: t("filters.jobFreelance") },
  ];
}

export function getExperienceOptions(t) {
  return [
    { value: "entry", label: t("filters.expEntry") },
    { value: "mid", label: t("filters.expMid") },
    { value: "senior", label: t("filters.expSenior") },
    { value: "executive", label: t("filters.expExecutive") },
  ];
}

export function getUpgradeContent(t) {
  return {
    features: [
      { title: t("upgrade.featureSwipeTitle"), description: t("upgrade.featureSwipeDesc"), icon: "zap" },
      { title: t("upgrade.featureResumeTitle"), description: t("upgrade.featureResumeDesc"), icon: "sparkles" },
      { title: t("upgrade.featureCoverTitle"), description: t("upgrade.featureCoverDesc"), icon: "rocket" },
      { title: t("upgrade.featureMatchTitle"), description: t("upgrade.featureMatchDesc"), icon: "check" },
    ],
    stats: [
      { value: "1M+", label: t("upgrade.statDownloads") },
      { value: "3M+", label: t("upgrade.statJobs") },
      { value: "4.8 ★", label: t("upgrade.statRating") },
    ],
    benefits: [
      { title: t("upgrade.benefitTimingTitle"), description: t("upgrade.benefitTimingDesc"), icon: "zap" },
      { title: t("upgrade.benefitInstantTitle"), description: t("upgrade.benefitInstantDesc"), icon: "rocket" },
      { title: t("upgrade.benefitAiTitle"), description: t("upgrade.benefitAiDesc"), icon: "sparkles" },
      { title: t("upgrade.benefitSuccessTitle"), description: t("upgrade.benefitSuccessDesc"), icon: "heart" },
    ],
  };
}

export function getAiSettingRows(t) {
  return [
    {
      id: "aiCoverLetter",
      title: t("aiSettings.coverLetter"),
      description: t("aiSettings.coverLetterDesc"),
      stat: t("aiSettings.coverLetterStat"),
    },
    {
      id: "aiResume",
      title: t("aiSettings.resume"),
      description: t("aiSettings.resumeDesc"),
      stat: t("aiSettings.resumeStat"),
    },
    {
      id: "reviewDocuments",
      title: t("aiSettings.reviewDocs"),
      description: t("aiSettings.reviewDocsDesc"),
      stat: t("aiSettings.reviewDocsStat"),
    },
    {
      id: "findResumeGaps",
      title: t("aiSettings.findGaps"),
      description: t("aiSettings.findGapsDesc"),
      stat: t("aiSettings.findGapsStat"),
    },
  ];
}

export function formatUploadedDate(lang, iso) {
  if (!iso) return "";
  const locale = lang === "fr" ? "fr-FR" : "en-US";
  return new Intl.DateTimeFormat(locale, {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(iso));
}

export function formatPostedDate(t, iso) {
  if (!iso) return "";
  const d = new Date(iso);
  const diff = Math.floor((Date.now() - d.getTime()) / (1000 * 60 * 60 * 24));
  if (diff <= 0) return t("swipe.postedToday");
  if (diff === 1) return t("swipe.postedOneDay");
  return t("swipe.postedDays", { n: diff });
}

export function getSeniorityLabel(t, job) {
  const m = {
    junior: t("swipe.entryLevel"),
    mid: t("swipe.midLevel"),
    senior: t("swipe.senior"),
    lead: t("swipe.lead"),
    principal: t("swipe.principal"),
  };
  return m[job?.seniority] || t("swipe.fullTime");
}

export function getWorkModelLabel(t, v) {
  const m = {
    remote: t("swipe.remote"),
    hybrid: t("swipe.hybrid"),
    onsite: t("swipe.inPerson"),
  };
  return m[v] || v || t("swipe.hybrid");
}

export function getIndustryFor(t, job) {
  const stack = (job?.tech_stack || []).join(" ").toLowerCase();
  const title = (job?.title || "").toLowerCase();
  if (title.includes("design")) return t("swipe.industryProductDesign");
  if (stack.includes("rust") || stack.includes("go") || stack.includes("postgres")) return t("swipe.industryInfrastructure");
  if (stack.includes("ml") || stack.includes("pytorch") || stack.includes("transformers")) return t("swipe.industryAiMl");
  if (title.includes("marketing") || title.includes("growth")) return t("swipe.industryMarketing");
  return t("swipe.industryTechnology");
}

export function getCompanySize(t, job) {
  const buckets = [
    t("swipe.companySize11"),
    t("swipe.companySize51"),
    t("swipe.companySize501"),
    t("swipe.companySize1001"),
  ];
  let h = 0;
  for (const c of job?.company || "") h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return buckets[h % buckets.length];
}

export function getDemoSwipeSuccessCopy(t, job) {
  const company = job?.company || "";
  return {
    title: t("swipe.demoApplied"),
    description: company
      ? t("swipe.demoAppliedDesc")
      : t("swipe.demoAppliedDesc"),
  };
}

export function getSwipeSuccessCopy(t, data, job) {
  const submission = data?.submission_status || "not_submitted";
  const pkg = data?.package_status || data?.application_status;
  const company = job?.company || "";

  if (data?.queued_for_generation || data?.generation_status === "pending_generation") {
    const queuedTitle = t("swipe.swipeQueued", { company });
    const queuedDesc = t("swipe.swipeQueuedDesc");
    return {
      title: queuedTitle === "swipe.swipeQueued" ? t("swipe.swipePackageFor", { company }) : queuedTitle,
      description: queuedDesc === "swipe.swipeQueuedDesc" ? t("swipe.swipePackageReady") : queuedDesc,
    };
  }

  if (data?.manual_fulfillment || data?.manual_status === "manual_review_needed") {
    return { title: t("swipe.swipePackageFor", { company }), description: t("swipe.swipePackageReady") };
  }

  if (submission === "prepared") {
    const reviewOn = readAiSettings().reviewDocuments;
    return {
      title: reviewOn ? t("swipe.swipeReadyReview") : t("swipe.swipeAppPrepared"),
      description: reviewOn
        ? t("swipe.swipeWaitingReview", { company })
        : t("swipe.swipeReadyApps", { company }),
    };
  }
  if (submission === "action_required" || submission === "blocked") {
    return { title: t("review.actionRequired"), description: t("swipe.swipeActionRequiredDesc") };
  }
  if (submission === "blocked_captcha") {
    return { title: t("swipe.swipeHumanVerification"), description: t("swipe.swipeHumanVerificationDesc") };
  }
  if (submission === "prepare_failed") {
    return { title: t("swipe.swipePackageGenerated"), description: t("swipe.swipePackageFailed") };
  }
  if (pkg === "generated_text_only") {
    return { title: t("swipe.swipeTextGenerated"), description: t("swipe.swipeTextGeneratedDesc") };
  }
  if (pkg === "needs_profile_data") {
    return { title: t("swipe.swipeMoreProfile"), description: t("swipe.swipeMoreProfileDesc") };
  }
  if (pkg === "needs_job_data") {
    return { title: t("swipe.swipeMoreJob"), description: t("swipe.swipeMoreJobDesc") };
  }
  if (pkg === "failed") {
    return { title: t("swipe.swipeAppSaved"), description: t("swipe.swipeAppSavedDesc") };
  }
  return {
    title: t("swipe.swipePackageFor", { company }),
    description: t("swipe.swipePackageReady"),
  };
}

export function getSwipeErrorMessage(t, e) {
  if (e?.code === "ECONNABORTED") return t("swipe.generationTimeout");
  const detail = e?.response?.data?.detail;
  if (typeof detail === "string") return detail;
  if (detail?.message) return detail.message;
  return t("toasts.swipeFailed");
}

export function getHistoryTabs(t) {
  return [
    { key: "right", label: t("history.generated"), testid: "history-tab-liked" },
    { key: "left", label: t("history.passed"), testid: "history-tab-skipped" },
  ];
}

export function getTrackerQuickFilters(t) {
  return [
    { key: "submitted", label: t("tracker.submitted") },
    { key: "pending", label: t("tracker.pending") },
    { key: "prepared", label: t("tracker.prepared") },
    { key: "action_required", label: t("tracker.actionRequired") },
  ];
}

export function getTrackerFilterTabs(t) {
  return [
    { key: "all", label: t("tracker.all") },
    { key: "action_required", label: t("tracker.actionRequired") },
    { key: "pending", label: t("tracker.pending") },
    { key: "submitted", label: t("tracker.submitted") },
    { key: "prepared", label: t("tracker.prepared") },
    { key: "failed", label: t("tracker.failed") },
    { key: "expired", label: t("tracker.expired") },
  ];
}

export function getTrackerEmptyCopy(t, filter) {
  const map = {
    all: t("tracker.emptyAll"),
    action_required: t("tracker.emptyActionRequired"),
    pending: t("tracker.emptyPending"),
    submitted: t("tracker.emptySubmitted"),
    prepared: t("tracker.emptyPrepared"),
    failed: t("tracker.emptyFailed"),
    expired: t("tracker.emptyExpired"),
  };
  return map[filter] || t("tracker.emptyDefault");
}

export function getApplicationDisplayStatuses(t) {
  return {
    prepared: {
      label: t("tracker.prepared"),
      stripLabel: t("tracker.ready"),
      cta: t("tracker.ready"),
      tintLight: "bg-blue-50 text-blue-900 ring-1 ring-blue-200/80",
      tintDark: "bg-blue-100 text-blue-800 ring-1 ring-blue-200",
      strip: "bg-blue-50 text-blue-900",
      dotLight: "bg-blue-500",
      dotDark: "bg-blue-300",
    },
    submitted: {
      label: t("tracker.submitted"),
      stripLabel: t("tracker.submitted"),
      cta: t("tracker.applied"),
      tintLight: "bg-emerald-50 text-emerald-900 ring-1 ring-emerald-200/80",
      tintDark: "bg-emerald-100 text-emerald-800 ring-1 ring-emerald-200",
      strip: "bg-emerald-50 text-emerald-900",
      dotLight: "bg-emerald-500",
      dotDark: "bg-emerald-400",
    },
    action_required: {
      label: t("tracker.actionRequired"),
      stripLabel: t("tracker.actionRequired"),
      cta: t("tracker.answerQuestions"),
      tintLight: "bg-orange-50 text-orange-900 ring-1 ring-orange-200/80",
      tintDark: "bg-orange-100 text-orange-800 ring-1 ring-orange-200",
      strip: "bg-orange-50 text-orange-900",
      dotLight: "bg-orange-500",
      dotDark: "bg-orange-400",
    },
    blocked_captcha: {
      label: t("tracker.securityCheck"),
      stripLabel: t("tracker.securityCheck"),
      cta: t("tracker.viewIssue"),
      tintLight: "bg-orange-50 text-orange-900 ring-1 ring-orange-200/80",
      tintDark: "bg-orange-100 text-orange-800 ring-1 ring-orange-200",
      strip: "bg-orange-50 text-orange-900",
      dotLight: "bg-orange-500",
      dotDark: "bg-orange-400",
    },
    pending: {
      label: t("tracker.appPending"),
      stripLabel: t("tracker.pending"),
      cta: t("tracker.finalizing"),
      tintLight: "bg-amber-50 text-amber-900 ring-1 ring-amber-200/80",
      tintDark: "bg-amber-100 text-amber-800 ring-1 ring-amber-200",
      strip: "bg-amber-50 text-amber-900",
      dotLight: "bg-amber-500",
      dotDark: "bg-amber-400",
    },
    failed: {
      label: t("tracker.needsAttention"),
      stripLabel: t("tracker.needsAttention"),
      cta: t("tracker.viewIssue"),
      tintLight: "bg-rose-50 text-rose-900 ring-1 ring-rose-200/80",
      tintDark: "bg-rose-100 text-rose-800 ring-1 ring-rose-200",
      strip: "bg-rose-50 text-rose-900",
      dotLight: "bg-rose-500",
      dotDark: "bg-rose-400",
    },
    expired: {
      label: t("tracker.expired"),
      stripLabel: t("tracker.expired"),
      cta: t("tracker.expired"),
      tintLight: "bg-zinc-100 text-zinc-700 ring-1 ring-zinc-200/80",
      tintDark: "bg-zinc-200 text-zinc-800 ring-1 ring-zinc-300",
      strip: "bg-zinc-100 text-zinc-700",
      dotLight: "bg-zinc-400",
      dotDark: "bg-zinc-500",
    },
  };
}

export function getProfileTabs(t) {
  return [
    { key: "resume", label: t("profile.resume"), icon: "FileText" },
    { key: "personal", label: t("profile.personal"), icon: "UserIcon" },
    { key: "documents", label: t("profile.documentsTab"), icon: "FolderOpen" },
  ];
}

export function getResumeSections(t) {
  return [
    { key: "certifications", title: t("profileSections.certifications"), countKey: null, add: t("profileSections.addCertifications") },
    { key: "awards", title: t("profileSections.awards"), countKey: "awards", add: t("profileSections.addAwards") },
    { key: "coursework", title: t("profileSections.coursework"), countKey: "coursework", add: t("profileSections.addCoursework") },
    { key: "languages", title: t("profileSections.languages"), countKey: "languages", add: t("profileSections.addLanguages") },
    { key: "skills", title: t("profileSections.skills"), countKey: "skills", add: t("profileSections.addSkills") },
  ];
}
