/** Landing page FAQ — adapted from Sprout, branded for Hirly. */

const FAQ_EN = [
  {
    id: "what-is",
    question: "1. What is Hirly?",
    answer: [
      {
        type: "p",
        bold: "Hirly is built for job seekers who don't want to spend time on repetitive application work.",
      },
      {
        type: "p",
        text: "After setting up your profile, you can apply with just a swipe or click. Hirly personalizes your materials, submits the application, and tracks everything automatically — turning a simple action into a complete application process.",
      },
    ],
  },
  {
    id: "how-works",
    question: "2. How does Hirly work?",
    answer: [
      {
        type: "li",
        parts: [
          { text: "You " },
          { bold: "set up your profile once" },
          { text: " with your experience, skills, and preferences." },
        ],
      },
      {
        type: "li",
        parts: [
          { text: "When you swipe on a job, you can apply instantly or answer " },
          { bold: "guided, job-specific questions" },
          { text: " that surface skills and experiences you may not even realize you've built." },
        ],
      },
      {
        type: "li",
        text: "Hirly uses that info to personalize your resume and cover letter, fill application questions, and prepare everything for submission.",
      },
      {
        type: "li",
        parts: [
          { text: "You " },
          { bold: "review, edit, and apply" },
          { text: " with a swipe or click. Hirly will submit and track for you." },
        ],
      },
    ],
  },
  {
    id: "swipe-apply",
    question: "3. How does the Swipe to Apply / Quick Apply feature work?",
    answer: [
      { type: "p", text: "It's simple." },
      {
        type: "p",
        parts: [
          { bold: "Swipe right or tap apply" },
          { text: " on a job you're interested in, and Hirly takes it from there. Using your profile and any guided inputs, Hirly personalizes your resume and cover letter for that role and prepares the application for submission. That's it." },
        ],
      },
    ],
  },
  {
    id: "customize",
    question: "4. Can I customize my applications?",
    answer: [
      { type: "p", text: "Yes." },
      {
        type: "p",
        parts: [
          { text: "Before applying, you can " },
          { bold: "review and edit everything" },
          { text: " — your resume, cover letter, tone, and phrasing. Hirly helps you move faster, but you have " },
          { bold: "full control" },
          { text: " over what gets submitted." },
        ],
      },
    ],
  },
  {
    id: "job-listings",
    question: "5. Where does Hirly find job listings?",
    answer: [
      {
        type: "p",
        parts: [
          { text: "Hirly pulls listings from " },
          { bold: "verified company career sites" },
          { text: ", job boards, and partner networks — all refreshed daily." },
        ],
      },
      {
        type: "p",
        text: "You can search across industries, locations, and work types (remote, hybrid, or on-site) directly within Hirly.",
      },
    ],
  },
  {
    id: "employers-know",
    question: "6. Will employers know if I used Hirly?",
    answer: [
      { type: "p", text: "No." },
      {
        type: "p",
        parts: [
          { text: "Hirly prepares role-specific resumes and cover letters for each application. What employers receive from you is a " },
          { bold: "polished, professional application" },
          { text: " tailored to the role." },
        ],
      },
    ],
  },
  {
    id: "ats-friendly",
    question: "7. Are resumes and cover letters generated by Hirly ATS-friendly?",
    answer: [
      { type: "p", text: "Yes." },
      {
        type: "p",
        parts: [
          { text: "Hirly formats everything so your application can be easily read by employers. " },
          { bold: "Rest assured, your application looks polished, professional, and ready for review." },
        ],
      },
    ],
  },
  {
    id: "technical-issue",
    question: "8. What should I do if I encounter a technical issue?",
    answer: [
      {
        type: "p",
        parts: [
          { text: "You can report any issue directly through " },
          { bold: "Settings → Feedback" },
          { text: " in the app or email us at " },
          { link: "hi@hirly.com", href: "mailto:hi@hirly.com" },
          { text: "." },
        ],
      },
      { type: "p", text: "Our team usually responds within 24 hours." },
    ],
  },
];

const FAQ_FR = [
  {
    id: "what-is",
    question: "1. Qu'est-ce que Hirly ?",
    answer: [
      {
        type: "p",
        bold: "Hirly est conçu pour les chercheurs d'emploi qui ne veulent pas perdre de temps sur des candidatures répétitives.",
      },
      {
        type: "p",
        text: "Après avoir configuré votre profil, postulez en un swipe ou un clic. Hirly personnalise vos documents, envoie la candidature et suit tout automatiquement — une action simple devient un processus complet.",
      },
    ],
  },
  {
    id: "how-works",
    question: "2. Comment fonctionne Hirly ?",
    answer: [
      {
        type: "li",
        parts: [
          { text: "Vous " },
          { bold: "configurez votre profil une fois" },
          { text: " avec votre expérience, vos compétences et vos préférences." },
        ],
      },
      {
        type: "li",
        parts: [
          { text: "Quand vous swipez une offre, postulez instantanément ou répondez à des " },
          { bold: "questions guidées spécifiques au poste" },
          { text: " qui mettent en avant des compétences que vous n'auriez peut-être pas pensé à mentionner." },
        ],
      },
      {
        type: "li",
        text: "Hirly utilise ces infos pour personnaliser votre CV et lettre de motivation, remplir les questions et préparer l'envoi.",
      },
      {
        type: "li",
        parts: [
          { text: "Vous " },
          { bold: "relisez, modifiez et postulez" },
          { text: " en un swipe ou un clic. Hirly envoie et suit pour vous." },
        ],
      },
    ],
  },
  {
    id: "swipe-apply",
    question: "3. Comment fonctionne le Swipe to Apply / Quick Apply ?",
    answer: [
      { type: "p", text: "C'est simple." },
      {
        type: "p",
        parts: [
          { bold: "Swipez à droite ou appuyez sur postuler" },
          { text: " sur une offre qui vous intéresse, et Hirly s'occupe du reste. Avec votre profil et vos réponses guidées, Hirly personnalise CV et lettre pour ce poste et prépare la candidature. C'est tout." },
        ],
      },
    ],
  },
  {
    id: "customize",
    question: "4. Puis-je personnaliser mes candidatures ?",
    answer: [
      { type: "p", text: "Oui." },
      {
        type: "p",
        parts: [
          { text: "Avant de postuler, vous pouvez " },
          { bold: "tout relire et modifier" },
          { text: " — CV, lettre, ton et formulations. Hirly vous fait gagner du temps, mais vous gardez le " },
          { bold: "contrôle total" },
          { text: " sur ce qui est envoyé." },
        ],
      },
    ],
  },
  {
    id: "job-listings",
    question: "5. Où Hirly trouve-t-il les offres d'emploi ?",
    answer: [
      {
        type: "p",
        parts: [
          { text: "Hirly agrège les offres de " },
          { bold: "sites carrières d'entreprises vérifiées" },
          { text: ", job boards et réseaux partenaires — actualisés chaque jour." },
        ],
      },
      {
        type: "p",
        text: "Recherchez par secteur, localisation et type de travail (remote, hybride ou sur site) directement dans Hirly.",
      },
    ],
  },
  {
    id: "employers-know",
    question: "6. Les employeurs sauront-ils que j'ai utilisé Hirly ?",
    answer: [
      { type: "p", text: "Non." },
      {
        type: "p",
        parts: [
          { text: "Hirly prépare des CV et lettres adaptés à chaque poste. Ce que reçoivent les recruteurs, c'est une " },
          { bold: "candidature soignée et professionnelle" },
          { text: " adaptée au rôle." },
        ],
      },
    ],
  },
  {
    id: "ats-friendly",
    question: "7. Les CV et lettres générés par Hirly sont-ils compatibles ATS ?",
    answer: [
      { type: "p", text: "Oui." },
      {
        type: "p",
        parts: [
          { text: "Hirly formate tout pour que votre candidature soit facilement lisible par les recruteurs. " },
          { bold: "Soyez rassuré : votre candidature paraît soignée, professionnelle et prête à être examinée." },
        ],
      },
    ],
  },
  {
    id: "technical-issue",
    question: "8. Que faire en cas de problème technique ?",
    answer: [
      {
        type: "p",
        parts: [
          { text: "Signalez tout problème via " },
          { bold: "Paramètres → Feedback" },
          { text: " dans l'app ou écrivez-nous à " },
          { link: "hi@hirly.com", href: "mailto:hi@hirly.com" },
          { text: "." },
        ],
      },
      { type: "p", text: "Notre équipe répond généralement sous 24 heures." },
    ],
  },
];

export function getLandingFaq(lang) {
  return lang === "fr" ? FAQ_FR : FAQ_EN;
}
