/** Landing page FAQ — adapted from Sprout, branded for Hirly. */

import { BRAND, supportMailto } from "./brand";

const SUPPORT_LINK = {
  link: BRAND.SUPPORT_EMAIL,
  href: supportMailto(),
};

const FAQ_EN = [
  {
    id: "what-is",
    question: "1. What is Hirly?",
    answer: [
      {
        type: "p",
        bold: "Hirly is built for job seekers who don't want to spend time on repetitive application work.",
      },
      {
        type: "p",
        text: "After setting up your profile, you can apply with just a swipe or click. Hirly personalizes your materials, submits the application, and tracks everything automatically — turning a simple action into a complete application process.",
      },
    ],
  },
  {
    id: "how-works",
    question: "2. How does Hirly work?",
    answer: [
      {
        type: "li",
        parts: [
          { text: "You " },
          { bold: "set up your profile once" },
          { text: " with your experience, skills, and preferences." },
        ],
      },
      {
        type: "li",
        parts: [
          { text: "When you swipe on a job, you can apply instantly or answer " },
          { bold: "guided, job-specific questions" },
          { text: " that surface skills and experiences you may not even realize you've built." },
        ],
      },
      {
        type: "li",
        text: "Hirly uses that info to personalize your resume and cover letter, fill application questions, and prepare everything for submission.",
      },
      {
        type: "li",
        parts: [
          { text: "You " },
          { bold: "review, edit, and apply" },
          { text: " with a swipe or click. Hirly will submit and track for you." },
        ],
      },
    ],
  },
  {
    id: "swipe-apply",
    question: "3. How does the Swipe to Apply / Quick Apply feature work?",
    answer: [
      { type: "p", text: "It's simple." },
      {
        type: "p",
        parts: [
          { bold: "Swipe right or tap apply" },
          { text: " on a job you're interested in, and Hirly takes it from there. Using your profile and any guided inputs, Hirly personalizes your resume and cover letter for that role and prepares the application for submission. That's it." },
        ],
      },
    ],
  },
  {
    id: "customize",
    question: "4. Can I customize my applications?",
    answer: [
      { type: "p", text: "Yes." },
      {
        type: "p",
        parts: [
          { text: "Before applying, you can " },
          { bold: "review and edit everything" },
          { text: " — your resume, cover letter, tone, and phrasing. Hirly helps you move faster, but you have " },
          { bold: "full control" },
          { text: " over what gets submitted." },
        ],
      },
    ],
  },
  {
    id: "job-listings",
    question: "5. Where does Hirly find job listings?",
    answer: [
      {
        type: "p",
        parts: [
          { text: "Hirly pulls listings from " },
          { bold: "verified company career sites" },
          { text: ", job boards, and partner networks — all refreshed daily." },
        ],
      },
      {
        type: "p",
        text: "You can search across industries, locations, and work types (remote, hybrid, or on-site) directly within Hirly.",
      },
    ],
  },
  {
    id: "employers-know",
    question: "6. Will employers know if I used Hirly?",
    answer: [
      { type: "p", text: "No." },
      {
        type: "p",
        parts: [
          { text: "Hirly prepares role-specific resumes and cover letters for each application. What employers receive from you is a " },
          { bold: "polished, professional application" },
          { text: " tailored to the role." },
        ],
      },
    ],
  },
  {
    id: "ats-friendly",
    question: "7. Are resumes and cover letters generated by Hirly ATS-friendly?",
    answer: [
      { type: "p", text: "Yes." },
      {
        type: "p",
        parts: [
          { text: "Hirly formats everything so your application can be easily read by employers. " },
          { bold: "Rest assured, your application looks polished, professional, and ready for review." },
        ],
      },
    ],
  },
  {
    id: "technical-issue",
    question: "8. What should I do if I encounter a technical issue?",
    answer: [
      {
        type: "p",
        parts: [
          { text: "You can report any issue directly through " },
          { bold: "Settings → Feedback" },
          { text: " in the app or email us at " },
          { link: SUPPORT_LINK.link, href: SUPPORT_LINK.href },
          { text: "." },
        ],
      },
      { type: "p", text: "Our team usually responds within 24 hours." },
    ],
  },
];

const FAQ_FR = [
  {
    id: "what-is",
    question: "1. Qu'est-ce que Hirly ?",
    answer: [
      {
        type: "p",
        bold: "Hirly est conçu pour les chercheurs d'emploi qui ne veulent pas perdre de temps sur des candidatures répétitives.",
      },
      {
        type: "p",
        text: "Après avoir configuré votre profil, postulez en un swipe ou un clic. Hirly personnalise vos documents, envoie la candidature et suit tout automatiquement — une action simple devient un processus complet.",
      },
    ],
  },
  {
    id: "how-works",
    question: "2. Comment fonctionne Hirly ?",
    answer: [
      {
        type: "li",
        parts: [
          { text: "Vous " },
          { bold: "configurez votre profil une fois" },
          { text: " avec votre expérience, vos compétences et vos préférences." },
        ],
      },
      {
        type: "li",
        parts: [
          { text: "Quand vous swipez une offre, postulez instantanément ou répondez à des " },
          { bold: "questions guidées spécifiques au poste" },
          { text: " qui mettent en avant des compétences que vous n'auriez peut-être pas pensé à mentionner." },
        ],
      },
      {
        type: "li",
        text: "Hirly utilise ces infos pour personnaliser votre CV et lettre de motivation, remplir les questions et préparer l'envoi.",
      },
      {
        type: "li",
        parts: [
          { text: "Vous " },
          { bold: "relisez, modifiez et postulez" },
          { text: " en un swipe ou un clic. Hirly envoie et suit pour vous." },
        ],
      },
    ],
  },
  {
    id: "swipe-apply",
    question: "3. Comment fonctionne le Swipe to Apply / Quick Apply ?",
    answer: [
      { type: "p", text: "C'est simple." },
      {
        type: "p",
        parts: [
          { bold: "Swipez à droite ou appuyez sur postuler" },
          { text: " sur une offre qui vous intéresse, et Hirly s'occupe du reste. Avec votre profil et vos réponses guidées, Hirly personnalise CV et lettre pour ce poste et prépare la candidature. C'est tout." },
        ],
      },
    ],
  },
  {
    id: "customize",
    question: "4. Puis-je personnaliser mes candidatures ?",
    answer: [
      { type: "p", text: "Oui." },
      {
        type: "p",
        parts: [
          { text: "Avant de postuler, vous pouvez " },
          { bold: "tout relire et modifier" },
          { text: " — CV, lettre, ton et formulations. Hirly vous fait gagner du temps, mais vous gardez le " },
          { bold: "contrôle total" },
          { text: " sur ce qui est envoyé." },
        ],
      },
    ],
  },
  {
    id: "job-listings",
    question: "5. Où Hirly trouve-t-il les offres d'emploi ?",
    answer: [
      {
        type: "p",
        parts: [
          { text: "Hirly agrège les offres de " },
          { bold: "sites carrières d'entreprises vérifiées" },
          { text: ", job boards et réseaux partenaires — actualisés chaque jour." },
        ],
      },
      {
        type: "p",
        text: "Recherchez par secteur, localisation et type de travail (remote, hybride ou sur site) directement dans Hirly.",
      },
    ],
  },
  {
    id: "employers-know",
    question: "6. Les employeurs sauront-ils que j'ai utilisé Hirly ?",
    answer: [
      { type: "p", text: "Non." },
      {
        type: "p",
        parts: [
          { text: "Hirly prépare des CV et lettres adaptés à chaque poste. Ce que reçoivent les recruteurs, c'est une " },
          { bold: "candidature soignée et professionnelle" },
          { text: " adaptée au rôle." },
        ],
      },
    ],
  },
  {
    id: "ats-friendly",
    question: "7. Les CV et lettres générés par Hirly sont-ils compatibles ATS ?",
    answer: [
      { type: "p", text: "Oui." },
      {
        type: "p",
        parts: [
          { text: "Hirly formate tout pour que votre candidature soit facilement lisible par les recruteurs. " },
          { bold: "Soyez rassuré : votre candidature paraît soignée, professionnelle et prête à être examinée." },
        ],
      },
    ],
  },
  {
    id: "technical-issue",
    question: "8. Que faire en cas de problème technique ?",
    answer: [
      {
        type: "p",
        parts: [
          { text: "Signalez tout problème via " },
          { bold: "Paramètres → Feedback" },
          { text: " dans l'app ou écrivez-nous à " },
          { link: SUPPORT_LINK.link, href: SUPPORT_LINK.href },
          { text: "." },
        ],
      },
      { type: "p", text: "Notre équipe répond généralement sous 24 heures." },
    ],
  },
];

const FAQ_DE = [
  {
    id: "what-is",
    question: "1. Was ist Hirly?",
    answer: [
      { type: "p", bold: "Hirly ist für Jobsuchende gemacht, die keine Zeit mit wiederholten Bewerbungsaufgaben verbringen möchten." },
      { type: "p", text: "Nachdem du dein Profil eingerichtet hast, kannst du dich mit einem Wisch oder Klick bewerben. Hirly personalisiert deine Unterlagen, reicht die Bewerbung ein und verfolgt alles automatisch — aus einer einfachen Aktion wird ein vollständiger Bewerbungsprozess." },
    ],
  },
  {
    id: "how-works",
    question: "2. Wie funktioniert Hirly?",
    answer: [
      { type: "li", parts: [{ text: "Du " }, { bold: "richtest dein Profil einmal ein" }, { text: " — mit deiner Erfahrung, deinen Fähigkeiten und Präferenzen." }] },
      { type: "li", parts: [{ text: "Wenn du bei einer Stelle swipest, kannst du dich sofort bewerben oder " }, { bold: "geführte, stellenbezogene Fragen" }, { text: " beantworten, die Fähigkeiten und Erfahrungen sichtbar machen, von denen du vielleicht nicht einmal weißt, dass du sie aufgebaut hast." }] },
      { type: "li", text: "Hirly nutzt diese Informationen, um deinen Lebenslauf und dein Anschreiben zu personalisieren, Bewerbungsfragen auszufüllen und alles für die Einreichung vorzubereiten." },
      { type: "li", parts: [{ text: "Du " }, { bold: "prüfst, bearbeitest und bewirbst dich" }, { text: " mit einem Wisch oder Klick. Hirly reicht die Bewerbung ein und verfolgt sie für dich." }] },
    ],
  },
  {
    id: "swipe-apply",
    question: "3. Wie funktioniert Swipe to Apply / Quick Apply?",
    answer: [
      { type: "p", text: "Ganz einfach." },
      { type: "p", parts: [{ bold: "Wische nach rechts oder tippe auf Bewerben" }, { text: " bei einer Stelle, die dich interessiert, und Hirly übernimmt den Rest. Mit deinem Profil und deinen geführten Angaben personalisiert Hirly deinen Lebenslauf und dein Anschreiben für diese Rolle und bereitet die Bewerbung zur Einreichung vor. Das ist alles." }] },
    ],
  },
  {
    id: "customize",
    question: "4. Kann ich meine Bewerbungen anpassen?",
    answer: [
      { type: "p", text: "Ja." },
      { type: "p", parts: [{ text: "Vor der Bewerbung kannst du " }, { bold: "alles prüfen und bearbeiten" }, { text: " — deinen Lebenslauf, dein Anschreiben, Ton und Formulierungen. Hirly hilft dir, schneller voranzukommen, aber du behältst die " }, { bold: "volle Kontrolle" }, { text: " darüber, was eingereicht wird." }] },
    ],
  },
  {
    id: "job-listings",
    question: "5. Woher bezieht Hirly Stellenanzeigen?",
    answer: [
      { type: "p", parts: [{ text: "Hirly bezieht Stellenanzeigen von " }, { bold: "verifizierten Karriereseiten von Unternehmen" }, { text: ", Jobbörsen und Partnernetzwerken — alle werden täglich aktualisiert." }] },
      { type: "p", text: "Direkt in Hirly kannst du branchen-, orts- und arbeitsformübergreifend suchen (remote, hybrid oder vor Ort)." },
    ],
  },
  {
    id: "employers-know",
    question: "6. Wissen Arbeitgeber, dass ich Hirly genutzt habe?",
    answer: [
      { type: "p", text: "Nein." },
      { type: "p", parts: [{ text: "Hirly erstellt für jede Bewerbung rollenbezogene Lebensläufe und Anschreiben. Arbeitgeber erhalten von dir eine " }, { bold: "sorgfältige, professionelle Bewerbung" }, { text: ", die auf die Stelle zugeschnitten ist." }] },
    ],
  },
  {
    id: "ats-friendly",
    question: "7. Sind die von Hirly erstellten Lebensläufe und Anschreiben ATS-freundlich?",
    answer: [
      { type: "p", text: "Ja." },
      { type: "p", parts: [{ text: "Hirly formatiert alles so, dass Arbeitgeber deine Bewerbung problemlos lesen können. " }, { bold: "Du kannst sicher sein: Deine Bewerbung wirkt professionell, sorgfältig und ist bereit für die Prüfung." }] },
    ],
  },
  {
    id: "technical-issue",
    question: "8. Was soll ich bei einem technischen Problem tun?",
    answer: [
      { type: "p", parts: [{ text: "Du kannst Probleme direkt über " }, { bold: "Einstellungen → Feedback" }, { text: " in der App melden oder uns eine E-Mail an " }, { link: SUPPORT_LINK.link, href: SUPPORT_LINK.href }, { text: "." }] },
      { type: "p", text: "Unser Team antwortet in der Regel innerhalb von 24 Stunden." },
    ],
  },
];

const FAQ_ES = [
  {
    id: "what-is",
    question: "1. ¿Qué es Hirly?",
    answer: [
      { type: "p", bold: "Hirly está pensado para quienes buscan empleo y no quieren dedicar tiempo a tareas repetitivas de solicitud." },
      { type: "p", text: "Después de configurar tu perfil, puedes postularte con un gesto o clic. Hirly personaliza tus documentos, envía la solicitud y hace seguimiento de todo automáticamente; así, una acción sencilla se convierte en un proceso de solicitud completo." },
    ],
  },
  {
    id: "how-works",
    question: "2. ¿Cómo funciona Hirly?",
    answer: [
      { type: "li", parts: [{ text: "Tú " }, { bold: "configuras tu perfil una sola vez" }, { text: " con tu experiencia, habilidades y preferencias." }] },
      { type: "li", parts: [{ text: "Cuando deslizas una oferta, puedes postularte al instante o responder " }, { bold: "preguntas guiadas y específicas para el puesto" }, { text: " que revelan habilidades y experiencias que quizá ni siquiera sabías que habías desarrollado." }] },
      { type: "li", text: "Hirly usa esa información para personalizar tu currículum y carta de presentación, completar las preguntas de la solicitud y prepararlo todo para el envío." },
      { type: "li", parts: [{ text: "Tú " }, { bold: "revisas, editas y te postulas" }, { text: " con un gesto o clic. Hirly lo enviará y hará seguimiento por ti." }] },
    ],
  },
  {
    id: "swipe-apply",
    question: "3. ¿Cómo funciona Swipe to Apply / Quick Apply?",
    answer: [
      { type: "p", text: "Es muy sencillo." },
      { type: "p", parts: [{ bold: "Desliza hacia la derecha o toca Postularme" }, { text: " en una oferta que te interese y Hirly se encarga del resto. Con tu perfil y las respuestas guiadas, Hirly personaliza tu currículum y carta de presentación para ese puesto y prepara la solicitud para enviarla. Eso es todo." }] },
    ],
  },
  {
    id: "customize",
    question: "4. ¿Puedo personalizar mis solicitudes?",
    answer: [
      { type: "p", text: "Sí." },
      { type: "p", parts: [{ text: "Antes de postularte, puedes " }, { bold: "revisar y editarlo todo" }, { text: " — tu currículum, carta de presentación, tono y redacción. Hirly te ayuda a avanzar más rápido, pero tienes el " }, { bold: "control total" }, { text: " sobre lo que se envía." }] },
    ],
  },
  {
    id: "job-listings",
    question: "5. ¿De dónde obtiene Hirly las ofertas de empleo?",
    answer: [
      { type: "p", parts: [{ text: "Hirly recopila ofertas de " }, { bold: "sitios de empleo verificados de empresas" }, { text: ", bolsas de empleo y redes de socios, todo actualizado a diario." }] },
      { type: "p", text: "Puedes buscar por sectores, ubicaciones y modalidades de trabajo (remoto, híbrido o presencial) directamente en Hirly." },
    ],
  },
  {
    id: "employers-know",
    question: "6. ¿Sabrán los empleadores que usé Hirly?",
    answer: [
      { type: "p", text: "No." },
      { type: "p", parts: [{ text: "Hirly prepara currículums y cartas de presentación específicos para cada puesto. Lo que reciben los empleadores es una " }, { bold: "solicitud cuidada y profesional" }, { text: " adaptada al puesto." }] },
    ],
  },
  {
    id: "ats-friendly",
    question: "7. ¿Los currículums y cartas de presentación de Hirly son compatibles con ATS?",
    answer: [
      { type: "p", text: "Sí." },
      { type: "p", parts: [{ text: "Hirly da formato a todo para que los empleadores puedan leer fácilmente tu solicitud. " }, { bold: "Puedes estar tranquilo: tu solicitud se ve cuidada, profesional y lista para revisarse." }] },
    ],
  },
  {
    id: "technical-issue",
    question: "8. ¿Qué debo hacer si tengo un problema técnico?",
    answer: [
      { type: "p", parts: [{ text: "Puedes informar de cualquier problema directamente desde " }, { bold: "Ajustes → Comentarios" }, { text: " en la aplicación o escribirnos a " }, { link: SUPPORT_LINK.link, href: SUPPORT_LINK.href }, { text: "." }] },
      { type: "p", text: "Nuestro equipo suele responder en un plazo de 24 horas." },
    ],
  },
];

const FAQ_IT = [
  {
    id: "what-is",
    question: "1. Che cos'è Hirly?",
    answer: [
      { type: "p", bold: "Hirly è pensato per chi cerca lavoro e non vuole perdere tempo con attività di candidatura ripetitive." },
      { type: "p", text: "Dopo aver configurato il tuo profilo, puoi candidarti con uno swipe o un clic. Hirly personalizza i tuoi documenti, invia la candidatura e tiene traccia di tutto automaticamente: un'azione semplice diventa un processo di candidatura completo." },
    ],
  },
  {
    id: "how-works",
    question: "2. Come funziona Hirly?",
    answer: [
      { type: "li", parts: [{ text: "Tu " }, { bold: "configuri il tuo profilo una sola volta" }, { text: " con esperienza, competenze e preferenze." }] },
      { type: "li", parts: [{ text: "Quando fai swipe su un'offerta, puoi candidarti subito o rispondere a " }, { bold: "domande guidate e specifiche per il ruolo" }, { text: " che mettono in luce competenze ed esperienze che potresti non renderti nemmeno conto di aver sviluppato." }] },
      { type: "li", text: "Hirly usa queste informazioni per personalizzare curriculum e lettera di presentazione, compilare le domande di candidatura e preparare tutto per l'invio." },
      { type: "li", parts: [{ text: "Tu " }, { bold: "rivedi, modifichi e ti candidi" }, { text: " con uno swipe o un clic. Hirly invierà la candidatura e ne terrà traccia per te." }] },
    ],
  },
  {
    id: "swipe-apply",
    question: "3. Come funziona Swipe to Apply / Quick Apply?",
    answer: [
      { type: "p", text: "È semplice." },
      { type: "p", parts: [{ bold: "Fai swipe a destra o tocca Candidati" }, { text: " su un'offerta che ti interessa e Hirly fa il resto. Usando il tuo profilo e le risposte guidate, Hirly personalizza curriculum e lettera di presentazione per quel ruolo e prepara la candidatura per l'invio. Tutto qui." }] },
    ],
  },
  {
    id: "customize",
    question: "4. Posso personalizzare le mie candidature?",
    answer: [
      { type: "p", text: "Sì." },
      { type: "p", parts: [{ text: "Prima di candidarti, puoi " }, { bold: "rivedere e modificare tutto" }, { text: " — curriculum, lettera di presentazione, tono e formulazioni. Hirly ti aiuta a fare prima, ma mantieni il " }, { bold: "controllo totale" }, { text: " su ciò che viene inviato." }] },
    ],
  },
  {
    id: "job-listings",
    question: "5. Dove trova Hirly gli annunci di lavoro?",
    answer: [
      { type: "p", parts: [{ text: "Hirly raccoglie annunci da " }, { bold: "siti di carriera aziendali verificati" }, { text: ", portali di lavoro e reti di partner, tutti aggiornati ogni giorno." }] },
      { type: "p", text: "Puoi cercare per settore, località e modalità di lavoro (da remoto, ibrido o in sede) direttamente in Hirly." },
    ],
  },
  {
    id: "employers-know",
    question: "6. I datori di lavoro sapranno che ho usato Hirly?",
    answer: [
      { type: "p", text: "No." },
      { type: "p", parts: [{ text: "Hirly prepara curriculum e lettere di presentazione specifici per ogni ruolo. Ciò che i datori di lavoro ricevono da te è una " }, { bold: "candidatura curata e professionale" }, { text: " su misura per il ruolo." }] },
    ],
  },
  {
    id: "ats-friendly",
    question: "7. I curriculum e le lettere di presentazione generati da Hirly sono compatibili con gli ATS?",
    answer: [
      { type: "p", text: "Sì." },
      { type: "p", parts: [{ text: "Hirly formatta tutto perché la tua candidatura possa essere letta facilmente dai datori di lavoro. " }, { bold: "Puoi stare tranquillo: la tua candidatura è curata, professionale e pronta per essere esaminata." }] },
    ],
  },
  {
    id: "technical-issue",
    question: "8. Cosa devo fare se riscontro un problema tecnico?",
    answer: [
      { type: "p", parts: [{ text: "Puoi segnalare qualsiasi problema direttamente tramite " }, { bold: "Impostazioni → Feedback" }, { text: " nell'app oppure scriverci a " }, { link: SUPPORT_LINK.link, href: SUPPORT_LINK.href }, { text: "." }] },
      { type: "p", text: "Il nostro team risponde di solito entro 24 ore." },
    ],
  },
];

export function getLandingFaq(lang) {
  const locale = normalizeLandingFaqLocale(lang);
  if (locale === "fr") return FAQ_FR;
  if (locale === "de") return FAQ_DE;
  if (locale === "es") return FAQ_ES;
  if (locale === "it") return FAQ_IT;
  return FAQ_EN;
}

export function getLandingFaqHeading(lang) {
  const locale = normalizeLandingFaqLocale(lang);
  if (locale === "fr") return "Questions fréquentes";
  if (locale === "de") return "Häufig gestellte Fragen";
  if (locale === "es") return "Preguntas frecuentes";
  if (locale === "it") return "Domande frequenti";
  return "Frequently asked questions";
}

function normalizeLandingFaqLocale(lang) {
  return String(lang || "").trim().toLowerCase().split("-")[0];
}
