/** French labels for onboarding job categories and roles (display only — English stored in profile). */

export const JOB_CATEGORY_LABELS_FR = {
  software: "Développement & ingénierie",
  healthcare: "Santé",
  consulting: "Conseil",
  data: "Data & analytics",
  design: "Design",
  finance: "Finance & comptabilité",
  legal: "Juridique",
  hr: "Ressources humaines",
  marketing: "Marketing & communication",
  operations: "Opérations & stratégie",
  product: "Produit",
  sales: "Commercial & ventes",
  customer: "Relation client",
  security: "Cybersécurité",
  engineering_other: "Autres métiers techniques",
  hospitality_food: "Restauration & hôtellerie",
  retail: "Commerce & vente en magasin",
  logistics: "Logistique & entrepôt",
  transport: "Transport & livraison",
  agriculture: "Agriculture & saisonnier",
  education_childcare: "Éducation & petite enfance",
  trades: "Bâtiment & artisans",
};

export const ONBOARDING_ROLE_LABELS_FR = {
  "Backend Engineer": "Ingénieur back-end",
  "Blockchain Engineer": "Ingénieur blockchain",
  "Cloud Engineer": "Ingénieur cloud",
  "Data Engineer": "Ingénieur data",
  "Developer Relations": "Developer relations",
  "DevOps Engineer": "Ingénieur DevOps",
  "Embedded Engineer": "Ingénieur embarqué",
  "Engineering Manager": "Engineering manager",
  "Frontend Engineer": "Ingénieur front-end",
  "Fullstack Engineer": "Ingénieur full stack",
  "Game Engineer": "Ingénieur jeu vidéo",
  "Machine Learning Engineer": "Ingénieur machine learning",
  "Mobile Engineer": "Ingénieur mobile",
  "Network Engineer": "Ingénieur réseau",
  "QA Engineer": "Ingénieur QA / test",
  "Sales Engineer": "Ingénieur avant-vente",
  "Software Engineer": "Ingénieur logiciel",
  "Site Reliability Engineer": "Ingénieur SRE",
  "Software Architect": "Architecte logiciel",
  "Support Engineer": "Ingénieur support",

  "Clinical Research Associate": "Attaché de recherche clinique",
  "Clinical Research Coordinator": "Coordinateur de recherche clinique",
  Epidemiologist: "Épidémiologiste",
  "Healthcare Administrator": "Administrateur santé",
  "Healthcare Manager": "Responsable santé",
  "Licensed Practical Nurse": "Infirmier·ère auxiliaire",
  "Medical Biller": "Gestionnaire facturation médicale",
  "Medical Coder": "Codeur médical",
  "Medical Director": "Directeur médical",
  "Medical Science Liaison": "Medical science liaison",
  "Mental Health Counselor": "Conseiller en santé mentale",
  "Nurse Practitioner": "Infirmier·ère praticien·ne",
  "Occupational Therapist": "Ergothérapeute",
  Pharmacist: "Pharmacien·ne",
  "Pharmacy Technician": "Préparateur·rice en pharmacie",
  "Physical Therapist": "Kinésithérapeute",
  Physician: "Médecin",
  "Public Health Analyst": "Analyste santé publique",
  "Radiologic Technologist": "Manipulateur·rice en radiologie",
  Radiologist: "Radiologue",
  "Registered Nurse": "Infirmier·ère diplômé·e",
  "Speech-Language Pathologist": "Orthophoniste",
  Surgeon: "Chirurgien·ne",
  "Surgical Technologist": "Instrumentiste",

  "Financial Consultant": "Consultant financier",
  "IT Consultant": "Consultant IT",
  "L&D Specialist": "Spécialiste formation",
  "Management Consultant": "Consultant en management",
  "Technology Consultant": "Consultant technologie",
  "Training Manager": "Responsable formation",

  "Data Analyst": "Analyste data",
  "Data Scientist": "Data scientist",
  "Research Engineer": "Ingénieur de recherche",
  "Salesforce Analyst": "Analyste Salesforce",

  "Brand Designer": "Designer de marque",
  "Graphic Designer": "Graphiste",
  "Industrial Designer": "Designer industriel",
  "Motion Designer": "Motion designer",
  "Product Designer": "Designer produit",
  "UI Designer": "Designer UI",
  "UX Designer": "Designer UX",

  Accountant: "Comptable",
  "Accounts Payable Specialist": "Comptable fournisseurs",
  "Accounts Receivable Specialist": "Comptable clients",
  Bookkeeper: "Aide-comptable",
  "Corporate Finance Manager": "Responsable finance d'entreprise",
  "Finance Operations Analyst": "Analyste opérations finance",
  "Financial Analyst": "Analyste financier",
  "Financial Auditor": "Auditeur financier",
  "Payroll Specialist": "Gestionnaire de paie",
  "Risk Analyst": "Analyste risques",

  "Compliance Officer": "Responsable conformité",
  "Legal Counsel": "Juriste",
  Paralegal: "Assistant·e juridique",

  "Executive Assistant": "Assistant·e de direction",
  "HR Business Partner": "HR business partner",
  "HR Generalist": "Généraliste RH",
  "HR Manager": "Responsable RH",
  "People Operations Manager": "Responsable people ops",
  Recruiter: "Recruteur·se",
  "Technical Recruiter": "Recruteur·se tech",

  "Brand Manager": "Chef·fe de marque",
  "Communications Specialist": "Chargé·e de communication",
  "Community Manager": "Community manager",
  "Content Marketing Manager": "Responsable content marketing",
  "Content Strategist": "Stratège contenu",
  Copywriter: "Rédacteur·rice",
  "Creative Director": "Directeur·rice de création",
  "Digital Marketing Manager": "Responsable marketing digital",
  "Digital Marketing Specialist": "Spécialiste marketing digital",
  "Event Manager": "Responsable événementiel",
  "Growth Hacker": "Growth hacker",
  "Growth Marketing Manager": "Responsable growth marketing",
  "Marketing Analyst": "Analyste marketing",
  "Marketing Generalist": "Généraliste marketing",
  "Marketing Operations Manager": "Responsable marketing ops",
  "Performance Marketing Manager": "Responsable performance marketing",
  "Product Marketing Manager": "Responsable marketing produit",
  "Public Relations Manager": "Responsable relations presse",
  "SEO Manager": "Responsable SEO",
  "SEO Specialist": "Spécialiste SEO",
  "Social Media Manager": "Social media manager",

  "Business Analyst": "Business analyst",
  "Business Operations Analyst": "Analyste opérations",
  "Business Operations Manager": "Responsable opérations",
  "Corporate Strategist": "Stratège d'entreprise",
  "Operations Associate": "Chargé·e d'opérations",
  "Operations Coordinator": "Coordinateur·rice d'opérations",
  "Program Manager": "Program manager",
  "Project Manager": "Chef·fe de projet",
  "Strategy Manager": "Responsable stratégie",
  "Supply Chain Analyst": "Analyste supply chain",
  "Supply Chain Manager": "Responsable supply chain",

  "Product Analyst": "Analyste produit",
  "Product Manager": "Chef·fe de produit",
  "Technical Product Manager": "Product manager technique",
  "User Researcher": "UX researcher",

  "Account Executive": "Account executive",
  "Account Manager": "Account manager",
  "Business Development Manager": "Responsable développement commercial",
  "Business Development Representative": "Business developer",
  "Channel Sales Manager": "Responsable ventes indirectes",
  "Enterprise Account Executive": "Account executive grands comptes",
  "Partnership Manager": "Responsable partenariats",
  "Sales Director": "Directeur·rice commercial·e",
  "Sales Manager": "Responsable commercial·e",
  "Sales Operations Analyst": "Analyste sales ops",
  "Sales Operations Manager": "Responsable sales ops",
  "Technical Account Manager": "Technical account manager",
  "VP of Sales": "Directeur·rice des ventes",

  "Customer Success Manager": "Customer success manager",
  "Customer Support Manager": "Responsable support client",
  "Customer Support Representative": "Conseiller·ère client",

  "Cybersecurity Analyst": "Analyste cybersécurité",
  "Cybersecurity Engineer": "Ingénieur cybersécurité",
  "Security Engineer": "Ingénieur sécurité",

  "Hardware Engineer": "Ingénieur hardware",
  "IT Support Specialist": "Technicien support IT",
  "Mechanical Engineer": "Ingénieur mécanique",
  "Technical Writer": "Rédacteur·rice technique",

  Server: "Serveur·se",
  Waiter: "Serveur",
  Waitress: "Serveuse",
  Bartender: "Barman / barmaid",
  "Restaurant Host": "Hôte·esse d'accueil",
  "Kitchen Porter": "Plongeur·se",
  Barista: "Barista",
  "Hotel Front Desk": "Réceptionniste hôtel",

  "Retail Sales Associate": "Vendeur·se",
  Cashier: "Caissier·ère",
  "Store Supervisor": "Chef·fe de rayon",
  "Visual Merchandiser": "Merchandiser",

  "Warehouse Worker": "Magasinier·ère",
  "Picker Packer": "Préparateur·rice de commandes",
  "Forklift Operator": "Cariste",
  "Inventory Clerk": "Gestionnaire de stocks",

  "Delivery Driver": "Livreur·se",
  Courier: "Coursier·ère",
  "Truck Driver": "Chauffeur·se routier·ère",
  "Ride-hail Driver": "Chauffeur VTC",

  "Farm Hand": "Ouvrier·ère agricole",
  "Fruit Picker": "Cueilleur·se de fruits",
  "Vineyard Worker": "Vendangeur·se",
  "Harvest Worker": "Travailleur·se saisonnier·ère",
  "Greenhouse Worker": "Ouvrier·se serriste",

  "Teaching Assistant": "Assistant·e pédagogique",
  "Childcare Worker": "Auxiliaire de petite enfance",
  "Camp Counselor": "Animateur·rice de colonie",
  Tutor: "Professeur·e particulier·ère",

  "Electrician Apprentice": "Apprenti·e électricien·ne",
  "Plumber Apprentice": "Apprenti·e plombier·e",
  "Construction Laborer": "Manœuvre BTP",
  "Carpenter Helper": "Aide charpentier",
};

export function translateOnboardingCategoryLabel(id, label, lang) {
  if (!lang || !String(lang).toLowerCase().startsWith("fr")) return label;
  return JOB_CATEGORY_LABELS_FR[id] || label;
}
