export const TRAINING_UI = {
  en: {
    academy: "Academy",
    videoCourses: "Video courses",
    backToApp: "Back to app",
    returnToBrand: "Return to {brand}",
    catalog: "Catalog",
    myLearning: "My learning",
    creatorStudio: "Creator studio",
    becomeCreator: "Become a creator",
    hubTitle: "Talking Heads",
    hubSubtitle: "Video scripts & lessons to level up your job search.",
    scrollHint: "Scroll down to see the lessons",
    viewDetails: "View course",
    startHere: "Start here",
    inProgress: "In progress",
    allCourses: "All courses",
    chapters: "Chapters",
    refBadge: "Ref",
    disclaimerTitle: "Important Notice: Confidentiality Agreement",
    disclaimerBody: "By accessing this document, you agree that it is strictly confidential. You are not authorized to share this document with anyone else, either through direct sharing, screenshots, or other means of distribution. Unauthorized sharing or distribution of this document will result in immediate revocation of access and may lead to further regulatory action.",
    disclaimerHelp: "If you have any questions about sharing this content, please contact the document owner for guidance.",
    titleColumn: "Title",
    levelColumn: "Level",
    courseCatalog: "Course catalog",
    myLearningTitle: "My learning",
    catalogSubtitle: "Structured lessons — best on desktop.",
    learningSubtitle: "Pick up where you left off.",
    noCourses: "No courses yet",
    noCoursesHint: "New courses will appear here once published.",
    noLearning: "No courses in progress",
    noLearningHint: "Browse the catalog and enroll in your first course.",
    browseCatalog: "Browse catalog",
    modules: "modules",
    min: "min",
    progress: "Progress",
    lessons: "lessons",
    lesson: "Lesson",
    courseContent: "Course content",
    courseModules: "Course modules",
    modulesHint: "Please go through all the videos and quizzes at the end of each module!",
    moduleLine: "Module {n}: {title}",
    moduleNumber: "Module {n}",
    yourProgress: "Your progress",
    ofCompleted: "{done} of {total} lessons completed",
    instructor: "Instructor",
    totalDuration: "min total",
    markComplete: "Mark lesson complete",
    next: "Next",
    completed: "Lesson completed",
    enrollSave: "Enroll to save progress",
    startCourse: "Start course",
    videoSoon: "Video coming soon",
    videoTitle: "Course video",
    courseCompleted: "Course completed!",
    loadError: "Could not load courses",
    courseNotFound: "Course not found",
    creatorUnlocked: "Creator studio unlocked",
    creatorError: "Could not register as creator",
    enrollError: "Could not enroll",
    saveError: "Could not save progress",
    levelBeginner: "Beginner",
    categories: {
      fundamentals: "Getting started",
      application: "Apply smarter",
      interview: "Interviews",
    },
    creator: {
      title: "Creator studio",
      subtitle: "Manage students, track progress, and run your course pipeline.",
      overview: "Overview",
      students: "Students",
      leads: "Leads CRM",
      pipeline: "Pipeline",
      recentStudents: "Recent students",
      student: "Student",
      course: "Course",
      updated: "Updated",
      addLead: "Add lead",
      saveLead: "Save lead",
      noEnrollments: "No enrollments yet.",
      noStudents: "No students enrolled yet.",
      noLeads: "No leads yet.",
      courses: "Courses",
      avgProgress: "Avg progress",
      leadsLabel: "Leads",
      accessRequired: "Creator access required",
      loadError: "Could not load studio",
      emailRequired: "Email is required",
      leadAdded: "Lead added",
      addLeadError: "Could not add lead",
      updateLeadError: "Could not update lead",
      saving: "Saving…",
      unnamedLead: "Unnamed lead",
      namePlaceholder: "Name",
      emailPlaceholder: "Email",
      notesPlaceholder: "Notes (optional)",
      studentFallback: "Student",
    },
    stages: {
      new: "New",
      contacted: "Contacted",
      qualified: "Qualified",
      enrolled: "Enrolled",
      won: "Won",
      lost: "Lost",
    },
  },
  fr: {
    academy: "Académie",
    videoCourses: "Cours vidéo",
    backToApp: "Retour à l'app",
    returnToBrand: "Retour sur {brand}",
    catalog: "Catalogue",
    myLearning: "Ma progression",
    creatorStudio: "Studio créateur",
    becomeCreator: "Devenir créateur",
    hubTitle: "Talking Heads",
    hubSubtitle: "Scripts vidéo et leçons pour booster ta recherche d'emploi.",
    scrollHint: "Fais défiler pour voir les leçons",
    viewDetails: "Voir le cours",
    startHere: "Commencer ici",
    inProgress: "En cours",
    allCourses: "Tous les cours",
    chapters: "Chapitres",
    disclaimerTitle: "Avis important : accord de confidentialité",
    disclaimerBody:
      "En accédant à ce document, tu acceptes qu'il est strictement confidentiel. Tu n'es pas autorisé(e) à le partager avec quiconque, que ce soit par partage direct, captures d'écran ou tout autre moyen de diffusion. Tout partage non autorisé entraînera la révocation immédiate de ton accès et pourra donner lieu à d'autres mesures.",
    disclaimerHelp:
      "Si tu as des questions sur le partage de ce contenu, contacte le propriétaire du document pour obtenir des conseils.",
    refBadge: "Réf",
    titleColumn: "Titre",
    levelColumn: "Niveau",
    courseCatalog: "Catalogue des cours",
    myLearningTitle: "Ma progression",
    catalogSubtitle: "Leçons structurées — idéal sur ordinateur.",
    learningSubtitle: "Reprends là où tu t'es arrêté.",
    noCourses: "Aucun cours pour l'instant",
    noCoursesHint: "Les nouveaux cours apparaîtront ici une fois publiés.",
    noLearning: "Aucun cours en cours",
    noLearningHint: "Parcours le catalogue et inscris-toi à ton premier cours.",
    browseCatalog: "Parcourir le catalogue",
    modules: "modules",
    min: "min",
    progress: "Progression",
    lessons: "leçons",
    lesson: "Leçon",
    courseContent: "Contenu du cours",
    courseModules: "Modules du cours",
    modulesHint: "Regarde toutes les vidéos et fais les quiz à la fin de chaque module !",
    moduleLine: "Module {n} : {title}",
    moduleNumber: "Module {n}",
    yourProgress: "Ta progression",
    ofCompleted: "{done} sur {total} leçons terminées",
    instructor: "Formateur",
    totalDuration: "min au total",
    markComplete: "Marquer comme terminé",
    next: "Suivant",
    completed: "Leçon terminée",
    enrollSave: "S'inscrire pour sauvegarder",
    startCourse: "Commencer le cours",
    videoSoon: "Vidéo bientôt disponible",
    videoTitle: "Vidéo du cours",
    courseCompleted: "Cours terminé !",
    loadError: "Impossible de charger les cours",
    courseNotFound: "Cours introuvable",
    creatorUnlocked: "Studio créateur débloqué",
    creatorError: "Impossible de s'inscrire comme créateur",
    enrollError: "Impossible de s'inscrire",
    saveError: "Impossible d'enregistrer la progression",
    levelBeginner: "Débutant",
    categories: {
      fundamentals: "Premiers pas",
      application: "Postuler malin",
      interview: "Entretiens",
    },
    creator: {
      title: "Studio créateur",
      subtitle: "Gère tes élèves, la progression et ton pipeline CRM.",
      overview: "Vue d'ensemble",
      students: "Élèves",
      leads: "CRM leads",
      pipeline: "Pipeline",
      recentStudents: "Élèves récents",
      student: "Élève",
      course: "Cours",
      updated: "Mis à jour",
      addLead: "Ajouter un lead",
      saveLead: "Enregistrer",
      noEnrollments: "Aucune inscription pour l'instant.",
      noStudents: "Aucun élève inscrit.",
      noLeads: "Aucun lead pour l'instant.",
      courses: "Cours",
      avgProgress: "Progression moy.",
      leadsLabel: "Leads",
      accessRequired: "Accès créateur requis",
      loadError: "Impossible de charger le studio",
      emailRequired: "L'e-mail est requis",
      leadAdded: "Lead ajouté",
      addLeadError: "Impossible d'ajouter le lead",
      updateLeadError: "Impossible de mettre à jour le lead",
      saving: "Enregistrement…",
      unnamedLead: "Lead sans nom",
      namePlaceholder: "Nom",
      emailPlaceholder: "E-mail",
      notesPlaceholder: "Notes (optionnel)",
      studentFallback: "Élève",
    },
    stages: {
      new: "Nouveau",
      contacted: "Contacté",
      qualified: "Qualifié",
      enrolled: "Inscrit",
      won: "Gagné",
      lost: "Perdu",
    },
  },
};

export function trainingT(lang, key, vars = {}) {
  const parts = key.split(".");
  let cur = TRAINING_UI[lang] || TRAINING_UI.en;
  for (const part of parts) {
    cur = cur?.[part];
  }
  if (typeof cur !== "string") return key;
  return Object.entries(vars).reduce(
    (text, [k, v]) => text.replace(`{${k}}`, String(v)),
    cur,
  );
}
